export const automationThemeOrder = [
  "calcul",
  "proportions",
  "algebre",
  "fonctions",
  "statistiques",
  "probabilites",
] as const;

export type AutomationTheme = (typeof automationThemeOrder)[number];

export const automationThemeLabels: Record<AutomationTheme, string> = {
  calcul: "Calcul numérique",
  proportions: "Proportions et évolutions",
  algebre: "Algèbre",
  fonctions: "Fonctions et suites",
  statistiques: "Statistiques",
  probabilites: "Probabilités",
};

export type AutomationQuestion = {
  id: string;
  theme: AutomationTheme;
  chapter: string;
  prompt: string;
  options: readonly string[];
  correctIndex: number;
  explanation: string;
  trap?: string;
};

export const automationQuestions: AutomationQuestion[] = [
  {
    id: "calcul-01",
    theme: "calcul",
    chapter: "Fractions",
    prompt: "Que vaut 3/4 + 1/6 ?",
    options: ["4/10", "5/12", "11/12", "7/8"],
    correctIndex: 2,
    explanation: "Le dénominateur commun est 12 : 3/4 = 9/12 et 1/6 = 2/12, donc la somme vaut 11/12.",
    trap: "Additionner directement les numérateurs et les dénominateurs.",
  },
  {
    id: "calcul-02",
    theme: "calcul",
    chapter: "Fractions",
    prompt: "Que vaut 5/6 − 1/4 ?",
    options: ["4/2", "7/12", "2/5", "3/8"],
    correctIndex: 1,
    explanation: "5/6 = 10/12 et 1/4 = 3/12, donc 5/6 − 1/4 = 7/12.",
    trap: "Soustraire les dénominateurs.",
  },
  {
    id: "calcul-03",
    theme: "calcul",
    chapter: "Inverse",
    prompt: "Quel est l’inverse du double de 7 ?",
    options: ["2/7", "1/9", "1/14", "14"],
    correctIndex: 2,
    explanation: "Le double de 7 est 14 ; son inverse est donc 1/14.",
    trap: "Calculer le double de l’inverse, qui vaut 2/7.",
  },
  {
    id: "calcul-04",
    theme: "calcul",
    chapter: "Puissances",
    prompt: "Que vaut 2⁻³ ?",
    options: ["−8", "−6", "1/6", "1/8"],
    correctIndex: 3,
    explanation: "Une puissance négative donne l’inverse : 2⁻³ = 1/2³ = 1/8.",
    trap: "Confondre exposant négatif et résultat négatif.",
  },
  {
    id: "calcul-05",
    theme: "calcul",
    chapter: "Puissances",
    prompt: "Que vaut (3² × 3⁴) / 3³ ?",
    options: ["3", "9", "27", "81"],
    correctIndex: 2,
    explanation: "On additionne puis on soustrait les exposants : 3^(2+4−3) = 3³ = 27.",
    trap: "Multiplier les exposants au lieu de les additionner.",
  },
  {
    id: "calcul-06",
    theme: "calcul",
    chapter: "Racine carrée",
    prompt: "Quelle est la valeur de √81 ?",
    options: ["−9", "9", "±9", "40,5"],
    correctIndex: 1,
    explanation: "Le symbole √ désigne la racine carrée positive : √81 = 9.",
    trap: "Répondre ±9 : ce sont les solutions de x² = 81, pas la valeur de √81.",
  },
  {
    id: "calcul-07",
    theme: "calcul",
    chapter: "Calcul décimal",
    prompt: "Que vaut 4,8 ÷ 0,6 ?",
    options: ["0,8", "8", "48", "80"],
    correctIndex: 1,
    explanation: "Multiplier les deux nombres par 10 donne 48 ÷ 6 = 8.",
    trap: "Déplacer la virgule dans un seul des deux nombres.",
  },
  {
    id: "calcul-08",
    theme: "calcul",
    chapter: "Écriture scientifique",
    prompt: "Que vaut (6 × 10⁵) × (3 × 10⁻²) ?",
    options: ["1,8 × 10³", "1,8 × 10⁴", "18 × 10⁷", "2 × 10³"],
    correctIndex: 1,
    explanation: "6 × 3 = 18 et 10⁵ × 10⁻² = 10³. Ainsi 18 × 10³ = 1,8 × 10⁴.",
    trap: "Oublier de remettre le résultat sous forme scientifique.",
  },
  {
    id: "calcul-09",
    theme: "calcul",
    chapter: "Ordre de grandeur",
    prompt: "Quel est le meilleur ordre de grandeur de 298 × 0,051 ?",
    options: ["0,15", "1,5", "15", "150"],
    correctIndex: 2,
    explanation: "298 ≈ 300 et 0,051 ≈ 0,05, donc le produit est proche de 300 × 0,05 = 15.",
    trap: "Perdre un facteur 10 en manipulant 0,05.",
  },
  {
    id: "calcul-10",
    theme: "calcul",
    chapter: "Quotient de fractions",
    prompt: "Que vaut (2/3) ÷ (4/5) ?",
    options: ["8/15", "5/6", "6/5", "3/10"],
    correctIndex: 1,
    explanation: "Diviser par 4/5 revient à multiplier par 5/4 : (2/3) × (5/4) = 10/12 = 5/6.",
    trap: "Multiplier par la fraction sans l’inverser.",
  },
  {
    id: "proportions-01",
    theme: "proportions",
    chapter: "Pourcentage d’une quantité",
    prompt: "Combien vaut 15 % de 240 ?",
    options: ["24", "30", "36", "40"],
    correctIndex: 2,
    explanation: "10 % de 240 vaut 24 et 5 % vaut 12 ; 15 % vaut donc 36.",
    trap: "Calculer seulement 10 %.",
  },
  {
    id: "proportions-02",
    theme: "proportions",
    chapter: "Coefficient multiplicateur",
    prompt: "Quel coefficient multiplicateur correspond à une hausse de 12 % ?",
    options: ["0,12", "0,88", "1,12", "1,2"],
    correctIndex: 2,
    explanation: "Une hausse de 12 % correspond à 1 + 12/100 = 1,12.",
    trap: "Choisir le taux 0,12 au lieu du coefficient 1,12.",
  },
  {
    id: "proportions-03",
    theme: "proportions",
    chapter: "Évolutions successives",
    prompt: "Une baisse de 20 % suivie d’une hausse de 20 % équivaut à :",
    options: ["aucune évolution", "une baisse de 4 %", "une hausse de 4 %", "une baisse de 40 %"],
    correctIndex: 1,
    explanation: "Le coefficient global est 0,8 × 1,2 = 0,96 : la valeur finale représente 96 % de l’initiale, soit une baisse de 4 %.",
    trap: "Additionner −20 % et +20 %.",
  },
  {
    id: "proportions-04",
    theme: "proportions",
    chapter: "Valeur initiale",
    prompt: "Après une hausse de 25 %, un prix vaut 150 €. Quel était le prix initial ?",
    options: ["112,50 €", "120 €", "125 €", "187,50 €"],
    correctIndex: 1,
    explanation: "Le prix initial est 150 ÷ 1,25 = 120 €.",
    trap: "Retirer directement 25 % de 150.",
  },
  {
    id: "proportions-05",
    theme: "proportions",
    chapter: "Proportion de proportion",
    prompt: "Dans un groupe, 3/8 des personnes sont internes. Parmi elles, 40 % sont majeures. Quelle proportion du groupe est à la fois interne et majeure ?",
    options: ["8 %", "15 %", "35 %", "43 %"],
    correctIndex: 1,
    explanation: "On multiplie les proportions : (3/8) × 0,40 = 0,15, soit 15 %.",
    trap: "Additionner 3/8 et 40 %.",
  },
  {
    id: "proportions-06",
    theme: "proportions",
    chapter: "Points de pourcentage",
    prompt: "Un taux passe de 32 % à 38 %. De combien augmente-t-il en points de pourcentage ?",
    options: ["6 points", "18,75 points", "32 points", "38 points"],
    correctIndex: 0,
    explanation: "L’écart est 38 − 32 = 6 points de pourcentage.",
    trap: "Répondre 18,75 %, qui est le taux d’évolution relatif.",
  },
  {
    id: "proportions-07",
    theme: "proportions",
    chapter: "Taux d’évolution",
    prompt: "Une quantité passe de 80 à 92. Quel est son taux d’évolution ?",
    options: ["12 %", "15 %", "20 %", "92 %"],
    correctIndex: 1,
    explanation: "L’augmentation est 12 et 12/80 = 0,15, soit 15 %.",
    trap: "Diviser l’écart par la valeur finale 92.",
  },
  {
    id: "proportions-08",
    theme: "proportions",
    chapter: "Évolution réciproque",
    prompt: "Après une baisse de 20 %, quelle hausse ramène exactement à la valeur initiale ?",
    options: ["20 %", "24 %", "25 %", "80 %"],
    correctIndex: 2,
    explanation: "Il faut multiplier 0,8 par 1,25 pour obtenir 1. La hausse réciproque est donc 25 %.",
    trap: "Croire que les taux opposés se compensent.",
  },
  {
    id: "proportions-09",
    theme: "proportions",
    chapter: "Évolutions successives",
    prompt: "Deux hausses successives de 10 % équivalent à une hausse de :",
    options: ["20 %", "21 %", "22 %", "100 %"],
    correctIndex: 1,
    explanation: "Le coefficient global est 1,1² = 1,21, soit une hausse de 21 %.",
    trap: "Additionner mécaniquement les deux taux.",
  },
  {
    id: "proportions-10",
    theme: "proportions",
    chapter: "Fréquence",
    prompt: "Dans un effectif de 120 élèves, 42 ont choisi une option. Quelle est leur proportion ?",
    options: ["28 %", "35 %", "42 %", "78 %"],
    correctIndex: 1,
    explanation: "42/120 = 7/20 = 0,35, donc 35 %.",
    trap: "Prendre l’effectif 42 pour un pourcentage.",
  },
  {
    id: "algebre-01",
    theme: "algebre",
    chapter: "Identité remarquable",
    prompt: "Quelle est la forme développée de (x + 3)² ?",
    options: ["x² + 9", "x² + 3x + 9", "x² + 6x + 9", "x² + 6"],
    correctIndex: 2,
    explanation: "(a + b)² = a² + 2ab + b², donc (x + 3)² = x² + 6x + 9.",
    trap: "Oublier le double produit 2 × x × 3.",
  },
  {
    id: "algebre-02",
    theme: "algebre",
    chapter: "Factorisation",
    prompt: "Quelle est une forme factorisée de 4x² − 9 ?",
    options: ["(2x − 3)²", "(4x − 3)(x + 3)", "(2x − 3)(2x + 3)", "(x − 9)(4x + 1)"],
    correctIndex: 2,
    explanation: "C’est une différence de deux carrés : (2x)² − 3² = (2x − 3)(2x + 3).",
    trap: "Confondre différence de carrés et carré d’une différence.",
  },
  {
    id: "algebre-03",
    theme: "algebre",
    chapter: "Équation du premier degré",
    prompt: "Quelle est la solution de 3x − 7 = 11 ?",
    options: ["x = 4/3", "x = 6", "x = 9", "x = 18"],
    correctIndex: 1,
    explanation: "3x = 18, donc x = 6.",
    trap: "Diviser 11 par 3 avant de déplacer −7.",
  },
  {
    id: "algebre-04",
    theme: "algebre",
    chapter: "Équation produit nul",
    prompt: "Quelles sont les solutions de (x − 2)(2x + 5) = 0 ?",
    options: ["{2 ; 5/2}", "{−2 ; −5/2}", "{2 ; −5/2}", "{−2 ; 5/2}"],
    correctIndex: 2,
    explanation: "Un produit est nul si l’un de ses facteurs est nul : x = 2 ou 2x + 5 = 0, soit x = −5/2.",
    trap: "Perdre le signe négatif en résolvant 2x + 5 = 0.",
  },
  {
    id: "algebre-05",
    theme: "algebre",
    chapter: "Signe d’un produit",
    prompt: "Sur quel ensemble (x − 1)(x + 4) est-il strictement positif ?",
    options: ["]−4 ; 1[", "]−∞ ; −4[ ∪ ]1 ; +∞[", "]−∞ ; 1[", "]−4 ; +∞["],
    correctIndex: 1,
    explanation: "Le produit de deux facteurs du premier degré est positif à l’extérieur des racines −4 et 1.",
    trap: "Choisir l’intervalle entre les deux racines.",
  },
  {
    id: "algebre-06",
    theme: "algebre",
    chapter: "Réduction",
    prompt: "Réduire 3(2x − 1) − 2(x + 4).",
    options: ["4x − 11", "4x + 5", "8x − 5", "x − 11"],
    correctIndex: 0,
    explanation: "3(2x − 1) − 2(x + 4) = 6x − 3 − 2x − 8 = 4x − 11.",
    trap: "Oublier que −2 multiplie aussi le terme +4.",
  },
  {
    id: "algebre-07",
    theme: "algebre",
    chapter: "Inéquation",
    prompt: "Résoudre −2x + 5 ≤ 1.",
    options: ["x ≤ −2", "x ≤ 2", "x ≥ −2", "x ≥ 2"],
    correctIndex: 3,
    explanation: "−2x ≤ −4. En divisant par −2, on inverse le sens : x ≥ 2.",
    trap: "Ne pas inverser le sens de l’inégalité en divisant par un nombre négatif.",
  },
  {
    id: "algebre-08",
    theme: "algebre",
    chapter: "Isolement d’une variable",
    prompt: "On a E = (a − b)/c avec c ≠ 0. Quelle expression donne a ?",
    options: ["a = E/c + b", "a = Ec + b", "a = Ec − b", "a = c/(E + b)"],
    correctIndex: 1,
    explanation: "Ec = a − b, donc a = Ec + b.",
    trap: "Diviser à nouveau par c au lieu de multiplier.",
  },
  {
    id: "algebre-09",
    theme: "algebre",
    chapter: "Somme d’inverses",
    prompt: "Pour x et y non nuls, que vaut 1/x + 1/y ?",
    options: ["2/(x + y)", "1/(x + y)", "(x + y)/(xy)", "xy/(x + y)"],
    correctIndex: 2,
    explanation: "Le dénominateur commun est xy : 1/x = y/(xy) et 1/y = x/(xy).",
    trap: "Écrire 1/(x + y).",
  },
  {
    id: "algebre-10",
    theme: "algebre",
    chapter: "Équation du second degré",
    prompt: "Quel est l’ensemble des solutions réelles de x² = 13 ?",
    options: ["{13}", "{√13}", "{−√13 ; √13}", "∅"],
    correctIndex: 2,
    explanation: "Les deux réels dont le carré vaut 13 sont −√13 et √13.",
    trap: "Ne conserver que la racine positive.",
  },
  {
    id: "algebre-11",
    theme: "algebre",
    chapter: "Identité remarquable",
    prompt: "Développer (2x − 0,5)².",
    options: ["4x² − 2x + 0,25", "4x² − x + 0,25", "2x² − 2x + 0,25", "4x² + 2x + 0,25"],
    correctIndex: 0,
    explanation: "(2x)² − 2 × 2x × 0,5 + 0,5² = 4x² − 2x + 0,25.",
    trap: "Mal calculer le double produit.",
  },
  {
    id: "algebre-12",
    theme: "algebre",
    chapter: "Factorisation",
    prompt: "Factoriser x² − 6x + 9.",
    options: ["(x − 3)²", "(x + 3)²", "(x − 9)(x + 1)", "x(x − 6) + 9"],
    correctIndex: 0,
    explanation: "x² − 6x + 9 = x² − 2 × 3 × x + 3² = (x − 3)².",
    trap: "Choisir (x + 3)², dont le terme central est +6x.",
  },
  {
    id: "fonctions-01",
    theme: "fonctions",
    chapter: "Coefficient directeur",
    prompt: "Une droite passe par A(−1 ; 2) et B(3 ; 10). Quel est son coefficient directeur ?",
    options: ["1/2", "2", "3", "4"],
    correctIndex: 1,
    explanation: "(10 − 2)/(3 − (−1)) = 8/4 = 2.",
    trap: "Diviser la différence des abscisses par celle des ordonnées.",
  },
  {
    id: "fonctions-02",
    theme: "fonctions",
    chapter: "Fonction affine",
    prompt: "Si f(x) = −3x + 4, que vaut f(2) ?",
    options: ["−10", "−2", "2", "10"],
    correctIndex: 1,
    explanation: "f(2) = −3 × 2 + 4 = −6 + 4 = −2.",
    trap: "Oublier le signe négatif devant 3.",
  },
  {
    id: "fonctions-03",
    theme: "fonctions",
    chapter: "Zéros d’une fonction",
    prompt: "Quels sont les zéros de f(x) = x² − 4 ?",
    options: ["−4 et 4", "−2 et 2", "2 seulement", "4 seulement"],
    correctIndex: 1,
    explanation: "x² − 4 = (x − 2)(x + 2), donc les zéros sont −2 et 2.",
    trap: "Confondre les racines avec le nombre 4.",
  },
  {
    id: "fonctions-04",
    theme: "fonctions",
    chapter: "Dérivation",
    prompt: "Si f(x) = 3x² − 2x + 1, quelle est f′(x) ?",
    options: ["6x − 2", "3x − 2", "6x + 1", "3x² − 2"],
    correctIndex: 0,
    explanation: "La dérivée de 3x² est 6x, celle de −2x est −2 et celle de la constante est 0.",
    trap: "Conserver la constante dans la dérivée.",
  },
  {
    id: "fonctions-05",
    theme: "fonctions",
    chapter: "Dérivation",
    prompt: "Sur ]0 ; +∞[, quelle est la dérivée de f(x) = 1/x ?",
    options: ["1/x²", "−1/x²", "−1/x", "x"],
    correctIndex: 1,
    explanation: "La dérivée de x⁻¹ est −x⁻², soit −1/x².",
    trap: "Oublier le signe négatif.",
  },
  {
    id: "fonctions-06",
    theme: "fonctions",
    chapter: "Fonction exponentielle",
    prompt: "Quelle est la dérivée de f(x) = e²ˣ ?",
    options: ["e²ˣ", "2eˣ", "2e²ˣ", "e²ˣ⁻¹"],
    correctIndex: 2,
    explanation: "Pour e^{u(x)}, la dérivée est u′(x)e^{u(x)}. Ici u′(x) = 2.",
    trap: "Oublier le facteur 2 issu de la dérivée de 2x.",
  },
  {
    id: "fonctions-07",
    theme: "fonctions",
    chapter: "Suite arithmétique",
    prompt: "Une suite arithmétique vérifie u₀ = 5 et a pour raison −2. Que vaut u₄ ?",
    options: ["−3", "−1", "3", "13"],
    correctIndex: 0,
    explanation: "u₄ = u₀ + 4r = 5 + 4 × (−2) = −3.",
    trap: "Ajouter seulement une fois la raison.",
  },
  {
    id: "fonctions-08",
    theme: "fonctions",
    chapter: "Suite géométrique",
    prompt: "Une suite géométrique vérifie v₁ = 3 et a pour raison 2. Que vaut v₄ ?",
    options: ["12", "18", "24", "48"],
    correctIndex: 2,
    explanation: "De v₁ à v₄, on multiplie trois fois par 2 : v₄ = 3 × 2³ = 24.",
    trap: "Utiliser 2⁴ au lieu de 2^(4−1).",
  },
  {
    id: "fonctions-09",
    theme: "fonctions",
    chapter: "Tangente",
    prompt: "La tangente à la courbe de f au point d’abscisse a est horizontale. Que peut-on affirmer ?",
    options: ["f(a) = 0", "f′(a) = 0", "f′(a) = a", "f(a) = a"],
    correctIndex: 1,
    explanation: "Le nombre dérivé est le coefficient directeur de la tangente. Une tangente horizontale a une pente nulle.",
    trap: "Confondre l’ordonnée du point avec la pente de la tangente.",
  },
  {
    id: "statistiques-01",
    theme: "statistiques",
    chapter: "Moyenne",
    prompt: "Quelle est la moyenne de 5, 7, 8 et 10 ?",
    options: ["7", "7,5", "8", "30"],
    correctIndex: 1,
    explanation: "(5 + 7 + 8 + 10)/4 = 30/4 = 7,5.",
    trap: "Oublier de diviser la somme par l’effectif.",
  },
  {
    id: "statistiques-02",
    theme: "statistiques",
    chapter: "Moyenne pondérée",
    prompt: "Une note de 10 a coefficient 2 et une note de 16 coefficient 1. Quelle est la moyenne pondérée ?",
    options: ["12", "13", "13,5", "18"],
    correctIndex: 0,
    explanation: "(10 × 2 + 16 × 1)/(2 + 1) = 36/3 = 12.",
    trap: "Faire la moyenne simple de 10 et 16.",
  },
  {
    id: "statistiques-03",
    theme: "statistiques",
    chapter: "Médiane",
    prompt: "Quelle est la médiane de la série ordonnée 2 ; 4 ; 4 ; 7 ; 9 ?",
    options: ["4", "5", "5,2", "7"],
    correctIndex: 0,
    explanation: "Avec cinq valeurs, la médiane est la troisième valeur : 4.",
    trap: "Calculer la moyenne à la place de la médiane.",
  },
  {
    id: "statistiques-04",
    theme: "statistiques",
    chapter: "Étendue",
    prompt: "Quelle est l’étendue de la série −3 ; 2 ; 8 ; 12 ?",
    options: ["9", "12", "15", "17"],
    correctIndex: 2,
    explanation: "L’étendue vaut maximum − minimum : 12 − (−3) = 15.",
    trap: "Oublier que soustraire −3 revient à ajouter 3.",
  },
  {
    id: "probabilites-01",
    theme: "probabilites",
    chapter: "Probabilité conditionnelle",
    prompt: "On sait que P(A) = 0,4 et P(B | A) = 0,5. Que vaut P(A ∩ B) ?",
    options: ["0,2", "0,4", "0,45", "0,9"],
    correctIndex: 0,
    explanation: "P(A ∩ B) = P(A) × P(B | A) = 0,4 × 0,5 = 0,2.",
    trap: "Additionner les deux probabilités.",
  },
  {
    id: "probabilites-02",
    theme: "probabilites",
    chapter: "Événement contraire",
    prompt: "Si P(A) = 0,27, que vaut P(non A) ?",
    options: ["−0,27", "0,27", "0,63", "0,73"],
    correctIndex: 3,
    explanation: "P(non A) = 1 − P(A) = 1 − 0,27 = 0,73.",
    trap: "Confondre événement contraire et probabilité négative.",
  },
  {
    id: "probabilites-03",
    theme: "probabilites",
    chapter: "Réunion d’événements",
    prompt: "A et B sont incompatibles, avec P(A) = 0,35 et P(B) = 0,40. Que vaut P(A ∪ B) ?",
    options: ["0,14", "0,35", "0,40", "0,75"],
    correctIndex: 3,
    explanation: "Pour des événements incompatibles, P(A ∪ B) = P(A) + P(B) = 0,75.",
    trap: "Multiplier les probabilités.",
  },
  {
    id: "probabilites-04",
    theme: "probabilites",
    chapter: "Tableau d’effectifs",
    prompt: "Parmi 30 élèves pratiquant un sport, 18 font aussi de la musique. Quelle est la probabilité conditionnelle de faire de la musique sachant que l’élève pratique un sport ?",
    options: ["0,4", "0,6", "1,2", "18"],
    correctIndex: 1,
    explanation: "Dans le groupe des 30 sportifs, 18 font de la musique : 18/30 = 0,6.",
    trap: "Utiliser l’effectif total d’un autre groupe ou garder 18 comme probabilité.",
  },
  {
    id: "probabilites-05",
    theme: "probabilites",
    chapter: "Arbre pondéré",
    prompt: "On a P(A) = 0,6, P(B | A) = 0,2 et P(B | non A) = 0,5. Que vaut P(B) ?",
    options: ["0,12", "0,20", "0,32", "0,70"],
    correctIndex: 2,
    explanation: "P(B) = 0,6 × 0,2 + 0,4 × 0,5 = 0,12 + 0,20 = 0,32.",
    trap: "Ne prendre en compte qu’une seule branche menant à B.",
  },
];
