import type { ExamCorrectionExercise } from "@/components/marketing/OfficialExamCorrection";

export const bac2025J1Pdf = "https://www.education.gouv.fr/sites/default/files/2025-06/baccalaur-at-g-n-ral-2025-math-matiques-440856.pdf";
export const bac2025J2Pdf = "https://www.education.gouv.fr/sites/default/files/2025-06/baccalaur-at-g-n-ral-2025-math-matiques-440988.pdf";

export const bac2025J1Exercises: readonly ExamCorrectionExercise[] = [
  {
    id: "2025-j1-ex1", title: "Exercice 1 — groupes sanguins", points: "5 points officiels", difficulty: "Intermédiaire",
    topics: "Probabilités conditionnelles, loi binomiale, espérance, variance, moyenne d’échantillon et inégalité de Bienaymé-Tchebychev.",
    skill: "Modéliser une situation probabiliste et contrôler des arrondis.",
    items: [
      { id: "2025-j1-ex1-1", label: "Questions 1 à 4", question: "Compléter l’arbre, retrouver une probabilité conditionnelle et celle d’un donneur universel.", notion: "Arbre pondéré et probabilités conditionnelles", recognition: "les groupes forment une partition et les probabilités d’un chemin se multiplient", reasoning: "Le groupe O représente 42 % de la population. La contribution connue au rhésus positif vaut 0,45×0,85+0,10×0,84+0,03×0,82=0,4911 ; le complément jusqu’à 0,8397 permet de retrouver la branche O.", calculations: ["P(B∩R)=0,10×0,84=0,084", "P(R|O)=(0,8397−0,4911)/0,42=0,83", "P(O∩non R)=0,42×0,17=0,0714"], redaction: "Les dix pointillés portent 0,45 ; 0,10 ; 0,03 ; 0,42 puis 0,85/0,15 ; 0,84/0,16 et 0,82/0,18. Les deux branches issues de O, absentes des pointillés, sont déterminées aux questions suivantes : 0,83 et 0,17.", result: "8,4 % sont à la fois du groupe B et rhésus positif ; 7,14 % sont donneurs universels.", commonError: "Soustraire des probabilités conditionnelles entre elles au lieu de décomposer P(R) par groupes." },
      { id: "2025-j1-ex1-2", label: "Question 5", question: "Étudier le nombre de donneurs universels parmi 100 personnes.", notion: "Loi binomiale", recognition: "100 essais assimilés indépendants, de même probabilité 0,0714", reasoning: "Le nombre de succès suit B(100 ; 0,0714). On calcule la probabilité cumulée jusqu’à 7, puis np et np(1−p).", calculations: ["P(X≤7)≈0,577", "E(X)=100×0,0714=7,14", "V(X)=100×0,0714×0,9286≈6,63"], redaction: "La valeur cumulée est arrondie au millième, conformément à la demande.", result: "X suit B(100 ; 0,0714), P(X≤7)≈0,577, E(X)=7,14 et V(X)≈6,63.", commonError: "Calculer seulement P(X=7), alors que “au plus 7” signifie X≤7." },
      { id: "2025-j1-ex1-3", label: "Question 6", question: "Dimensionner le nombre de villes avec Bienaymé-Tchebychev.", notion: "Moyenne de variables indépendantes", recognition: "l’intervalle ]7 ; 7,28[ s’écrit |Mₙ−7,14|<0,14", reasoning: "La moyenne représente le nombre moyen de donneurs universels par échantillon de 100 personnes. Par indépendance, sa variance est divisée par N ; Bienaymé-Tchebychev minore ensuite la probabilité recherchée.", calculations: ["E(Mₙ)=7,14 ; V(Mₙ)=6,63/N", "P(|Mₙ−7,14|<0,14)≥1−6,63/(0,14²N)", "1−6,63/(0,0196N)≥0,95 ⇔ N≥6765,31"], redaction: "On choisit le premier entier qui satisfait la garantie fournie par l’inégalité.", result: "La plus petite valeur garantie est N=6 766 villes.", commonError: "Présenter la borne de Tchebychev comme une probabilité exacte." },
    ],
  },
  {
    id: "2025-j1-ex2", title: "Exercice 2 — fonction logarithmique et aire", points: "6 points officiels", difficulty: "Soutenue",
    topics: "Lecture graphique, dérivation, convexité, logarithme, tangente et intégration par parties.",
    skill: "Relier un graphique, une étude analytique et un calcul d’aire.",
    items: [
      { id: "2025-j1-ex2-a", label: "Partie A", question: "Lire une pente, les extremums et la convexité.", notion: "Dérivées et lecture graphique", recognition: "une pente de tangente donne f′ et une tangente horizontale correspond à f′=0", reasoning: "La droite passant par A(1;2) et C(3;0) a pour pente −1. Le graphique montre deux tangentes horizontales et une courbure vers le bas en 0,2.", calculations: ["f′(1)=(0−2)/(3−1)=−1"], redaction: "Les réponses sont justifiées par la pente et l’allure locale de la courbe.", result: "f′(1)=−1 ; deux solutions à f′(x)=0 sur ]0;3] ; f″(0,2)<0.", commonError: "Lire f(1) au lieu de f′(1)." },
      { id: "2025-j1-ex2-b12", label: "Partie B · questions 1 et 2", question: "Prouver que la courbe reste au-dessus de l’axe et déterminer la limite.", notion: "Trinôme et limites", recognition: "le facteur x est positif et le trinôme en ln x a un discriminant négatif", reasoning: "2X²−3X+2 a un discriminant −7 et un coefficient dominant positif. Le facteur logarithmique est donc toujours positif ; lorsque x tend vers +∞, le terme 2x(ln x)² domine.", calculations: ["Δ=9−16=−7", "f(x)=x(2(ln x)²−3ln x+2)>0"], redaction: "La courbe ne coupe donc pas l’axe des abscisses sur son domaine.", result: "f(x)>0 sur ]0;+∞[ et lim f(x)=+∞ en +∞.", commonError: "Conclure seulement à partir de x>0 sans étudier le trinôme." },
      { id: "2025-j1-ex2-b3", label: "Partie B · question 3", question: "Étudier la convexité et la position par rapport à la tangente en e.", notion: "Dérivée seconde et tangente", recognition: "le signe de f″ dépend de 4ln x+1", reasoning: "Le changement de signe a lieu lorsque x=e^(−1/4). La fonction est ensuite convexe, notamment sur [1;+∞[, donc sa courbe est au-dessus de chacune de ses tangentes sur cet intervalle.", calculations: ["f″(x)=(4ln x+1)/x", "4ln x+1=0 ⇔ x=e^(−1/4)"], redaction: "La concavité précède le point d’inflexion, puis la convexité lui succède.", result: "f est concave sur ]0;e^(−1/4)[, convexe sur ]e^(−1/4);+∞[ ; C_f est au-dessus de T_B sur [1;+∞[.", commonError: "Inverser concavité et convexité en oubliant que x>0 ne change pas le signe." },
      { id: "2025-j1-ex2-c", label: "Partie C", question: "Déterminer la tangente, intégrer par parties et calculer l’aire hachurée.", notion: "Tangente et intégrale", recognition: "sur [1;e], la convexité fixe l’ordre entre la courbe et T_B", reasoning: "On utilise f(e)=e et f′(e)=2. Une intégration par parties donne l’intégrale de x ln x ; les deux intégrales fournies permettent ensuite d’intégrer f−(2x−e).", calculations: ["T_B : y=2x−e", "∫₁ᵉ x ln(x)dx=(e²+1)/4", "A=∫₁ᵉ[f(x)−(2x−e)]dx=(3e²−4e−5)/4"], redaction: "L’aire est positive car la courbe se situe au-dessus de sa tangente sur l’intervalle.", result: "A=(3e²−4e−5)/4 unité d’aire.", commonError: "Intégrer T_B−f et obtenir l’opposé d’une aire." },
    ],
  },
  {
    id: "2025-j1-ex3", title: "Exercice 3 — quatre affirmations de géométrie", points: "4 points officiels", difficulty: "Intermédiaire",
    topics: "Droites et plans de l’espace, orthogonalité, coplanarité et distance d’un point à un plan.",
    skill: "Démontrer ou réfuter une affirmation par un calcul court.",
    items: [
      { id: "2025-j1-ex3-1", label: "Affirmation 1", question: "La représentation paramétrique décrit-elle (AB) ?", notion: "Droite paramétrique", recognition: "il faut vérifier un point et la colinéarité des vecteurs directeurs", reasoning: "Pour t=0, on obtient B. Le vecteur directeur (−2;−1;3) est colinéaire à AB=(4;2;−6).", calculations: ["AB=−2(−2;−1;3)"], redaction: "Le point B appartient à la droite proposée et les directions sont colinéaires.", result: "Affirmation vraie.", commonError: "Comparer seulement les coordonnées d’un point sans vérifier la direction." },
      { id: "2025-j1-ex3-2", label: "Affirmation 2", question: "Le vecteur proposé est-il normal au plan (OAB) ?", notion: "Vecteur normal", recognition: "un normal doit être orthogonal à deux directions non colinéaires du plan", reasoning: "Le produit scalaire avec OA est nul, mais celui avec OB ne l’est pas.", calculations: ["(5;−2;1)·OB=15−4−1=10"], redaction: "Une seule orthogonalité ne suffit pas pour être normal au plan.", result: "Affirmation fausse.", commonError: "S’arrêter après le premier produit scalaire nul." },
      { id: "2025-j1-ex3-3", label: "Affirmation 3", question: "Les deux droites sont-elles non coplanaires ?", notion: "Intersection de droites", recognition: "deux droites sécantes sont nécessairement coplanaires", reasoning: "Le système des trois coordonnées admet s=2,5 et k=−4, donnant le même point.", calculations: ["d(−4)=(11;12;−14)=d′(2,5)"], redaction: "Les droites sont sécantes ; elles appartiennent donc à un même plan.", result: "Affirmation fausse.", commonError: "Conclure à partir de directions non colinéaires : cela n’exclut pas une intersection." },
      { id: "2025-j1-ex3-4", label: "Affirmation 4", question: "Calculer la distance de C au plan.", notion: "Distance point-plan", recognition: "le numérateur est la valeur absolue de l’équation au point", reasoning: "On applique la formule avec le vecteur normal (1;−1;1).", calculations: ["d(C,P)=|2−(−1)+2+1|/√3=6/√3=2√3"], redaction: "Le dénominateur est la norme du vecteur normal.", result: "Affirmation vraie.", commonError: "Oublier la constante +1 dans le numérateur." },
    ],
  },
  {
    id: "2025-j1-ex4", title: "Exercice 4 — évolution de la posidonie", points: "5 points officiels", difficulty: "Soutenue",
    topics: "Suite récurrente, récurrence, convergence, Python, équation différentielle logistique et exponentielle.",
    skill: "Comparer un modèle discret et un modèle continu.",
    items: [
      { id: "2025-j1-ex4-a12", label: "Partie A · questions 1 et 2", question: "Étudier la suite de superficies et sa limite.", notion: "Suite récurrente et convergence monotone", recognition: "la fonction h est croissante sur l’intervalle invariant", reasoning: "u₁ vaut 1,28. L’initialisation puis la croissance de h donnent 1≤uₙ≤uₙ₊₁≤20. La suite croissante et majorée converge ; la relation de récurrence impose L=0 ou L=15, et L≥1 exclut 0.", calculations: ["u₁=−0,02×1²+1,3×1=1,28", "L=−0,02L²+1,3L ⇔ 0,02L(15−L)=0"], redaction: "La continuité du polynôme autorise le passage à la limite.", result: "La suite converge vers 15 hectares.", commonError: "Choisir L=0 sans utiliser la minoration uₙ≥1." },
      { id: "2025-j1-ex4-a3", label: "Partie A · question 3", question: "Justifier le franchissement de 14 ha et compléter l’algorithme.", notion: "Limite et boucle while", recognition: "une suite qui converge vers 15 finit par dépasser 14", reasoning: "La boucle continue tant que u≤14, incrémente l’année et applique la relation de récurrence.", calculations: ["while u <= 14:", "n = n + 1", "u = -0.02*u**2 + 1.3*u", "u₁₇≈13,791 ; u₁₈≈14,124"], redaction: "Le seuil est franchi pour la première fois à l’indice 18.", result: "Le modèle discret prévoit plus de 14 ha au 1er juillet 2042.", commonError: "Utiliser while u<14 et oublier que la question demande strictement plus de 14." },
      { id: "2025-j1-ex4-b123", label: "Partie B · questions 1 à 3", question: "Transformer puis résoudre l’équation différentielle logistique.", notion: "Équation différentielle", recognition: "le changement g=1/f rend l’équation linéaire", reasoning: "Comme f ne s’annule pas, g′=−f′/f²=−0,3g+0,02. Les solutions sont g(t)=Ce^(−0,3t)+1/15 et g(0)=1 donne C=14/15.", calculations: ["g(t)=(14/15)e^(−0,3t)+1/15", "f(t)=15/(14e^(−0,3t)+1)"], redaction: "Le passage à l’inverse est licite grâce à l’hypothèse f non nulle.", result: "f(t)=15/(14e^(−0,3t)+1).", commonError: "Dériver 1/f comme 1/f′." },
      { id: "2025-j1-ex4-b45", label: "Partie B · questions 4 et 5", question: "Trouver la limite et le moment où la surface dépasse 14 ha.", notion: "Limite et inéquation exponentielle", recognition: "le dénominateur est positif", reasoning: "L’exponentielle tend vers 0, donc f tend vers 15. Pour l’inéquation, les transformations conservent leur sens et conduisent à e^(−0,3t)<1/196.", calculations: ["t>ln(196)/0,3≈17,59"], redaction: "Le modèle continu situe le franchissement environ 17,6 ans après le 1er juillet 2024.", result: "lim f=15 et f(t)>14 pour t>ln(196)/0,3.", commonError: "Changer à tort le sens de l’inégalité avant d’avoir vérifié la positivité du dénominateur." },
    ],
  },
] as const;

export const bac2025J2Exercises: readonly ExamCorrectionExercise[] = [
  {
    id: "2025-j2-ex1", title: "Exercice 1 — centre multisports", points: "5 points officiels", difficulty: "Intermédiaire",
    topics: "Probabilités conditionnelles, loi binomiale, sommes de variables aléatoires et Bienaymé-Tchebychev.",
    skill: "Interpréter des probabilités et agréger des temps d’attente.",
    items: [
      { id: "2025-j2-ex1-a14", label: "Partie A · questions 1 à 4", question: "Construire l’arbre des chutes et calculer les probabilités demandées.", notion: "Arbre pondéré et conditionnement", recognition: "B se décompose selon A et son contraire", reasoning: "Les branches portent 0,6/0,4 puis 0,3/0,7 et 0,4/0,6. La probabilité demandée en question 2 est bien celle de ne chuter à aucune séance.", calculations: ["P(non A∩non B)=0,4×0,6=0,24", "P(B)=0,6×0,3+0,4×0,4=0,34", "P(non A|non B)=0,24/0,66=4/11≈0,364"], redaction: "P(non A∩non B)=0,24 signifie que 24 % des inscrits ne chutent lors d’aucune des deux séances.", result: "P(non A∩non B)=0,24 ; P(B)=0,34 ; P(non A|non B)≈0,364.", commonError: "Une extraction PDF peut masquer les barres : la question 2 porte sur non A et non B, pas sur A et B." },
      { id: "2025-j2-ex1-a5", label: "Partie A · question 5", question: "Compter les personnes qui ne chutent à aucune séance.", notion: "Loi binomiale", recognition: "100 répétitions indépendantes avec p=0,24", reasoning: "X suit B(100;0,24). “Au moins 20” correspond à 1−P(X≤19).", calculations: ["P(X≥20)=1−P(X≤19)≈0,855", "E(X)=100×0,24=24"], redaction: "Sur de nombreux échantillons, on attend en moyenne 24 personnes sans chute.", result: "X suit B(100;0,24), P(X≥20)≈0,855 et E(X)=24.", commonError: "Utiliser 0,34, qui est la probabilité de chuter à la deuxième séance." },
      { id: "2025-j2-ex1-b", label: "Partie B", question: "Étudier le temps total d’attente sur deux jours.", notion: "Somme de variables indépendantes", recognition: "les espérances s’ajoutent toujours ; les variances s’ajoutent ici grâce à l’indépendance", reasoning: "T=T₁+T₂. L’intervalle ]60;140[ s’écrit |T−100|<40 ; Tchebychev minore alors la probabilité.", calculations: ["E(T)=40+60=100 min", "V(T)=10²+16²=356 min²", "P(|T−100|<40)≥1−356/40²=0,7775>0,77"], redaction: "Le temps total moyen d’attente est de 100 minutes sur le week-end.", result: "E(T)=100, V(T)=356 et P(60<T<140)>0,77.", commonError: "Additionner les écarts-types au lieu des variances." },
    ],
  },
  {
    id: "2025-j2-ex2", title: "Exercice 2 — droites, plan et projection", points: "5 points officiels", difficulty: "Soutenue",
    topics: "Géométrie dans l’espace, équation de plan, projection orthogonale, distance et produit scalaire.",
    skill: "Enchaîner plusieurs caractérisations vectorielles.",
    items: [
      { id: "2025-j2-ex2-a1", label: "Partie A · question 1", question: "Vérifier l’intersection des deux droites.", notion: "Représentation paramétrique", recognition: "un même point doit être obtenu avec un paramètre propre à chaque droite", reasoning: "Dans d, t=−1 donne S ; dans d′, s=−1/2 donne aussi S.", calculations: ["d(−1)=d′(−1/2)=(−1/2;1;4)"], redaction: "Le point S appartient aux deux droites.", result: "d et d′ sont sécantes en S.", commonError: "Imposer le même paramètre aux deux représentations." },
      { id: "2025-j2-ex2-a2", label: "Partie A · question 2", question: "Établir l’équation du plan et la non-coplanarité de S.", notion: "Vecteur normal et plan", recognition: "un normal est orthogonal à AB et AC", reasoning: "n=(1;2;4) a des produits scalaires nuls avec AB=(2;−3;1) et AC=(2;−1;0). Le point A fixe la constante −7. En S, le membre de gauche vaut 10,5.", calculations: ["n·AB=0 ; n·AC=0", "−1/2+2+16−7=21/2≠0"], redaction: "S n’appartient pas au plan (ABC), donc A, B, C, S ne sont pas coplanaires.", result: "(ABC): x+2y+4z−7=0 et S∉(ABC).", commonError: "Oublier de vérifier que AB et AC ne sont pas colinéaires." },
      { id: "2025-j2-ex2-a3", label: "Partie A · question 3", question: "Identifier la projection et la distance minimale au plan.", notion: "Projeté orthogonal", recognition: "H doit appartenir au plan et SH être colinéaire au normal", reasoning: "H vérifie l’équation du plan et SH=(−1/2;−1;−2)=−(1/2)n. La distance minimale de S au plan est donc SH.", calculations: ["SH=√(1/4+1+4)=√21/2"], redaction: "Tout point M du plan vérifie SM≥SH.", result: "H est le projeté ; aucun M du plan ne vérifie SM<√21/2.", commonError: "Conclure à la projection en vérifiant seulement que H appartient au plan." },
      { id: "2025-j2-ex2-b", label: "Partie B", question: "Chercher un point M de [CS] rendant MAB rectangle en M.", notion: "Produit scalaire", recognition: "MAB est rectangle en M si MA·MB=0", reasoning: "Avec CM=kCS, M=(1−3k/2;1;1+3k). Le produit scalaire donne une équation du second degré dont une seule racine appartient à [0;1].", calculations: ["MA·MB=(45k²−24k−8)/4", "k=(4±2√14)/15", "k=(4+2√14)/15≈0,766"], redaction: "La seconde racine est négative ; elle ne décrit pas un point du segment.", result: "Oui, il existe un unique point, pour k=(4+2√14)/15.", commonError: "Tester l’orthogonalité de AB et AM au lieu de MA et MB." },
    ],
  },
  {
    id: "2025-j2-ex3", title: "Exercice 3 — quatre affirmations", points: "4 points officiels", difficulty: "Accessible",
    topics: "Croissance exponentielle d’une suite, récurrence, convexité graphique et inégalité logarithmique.",
    skill: "Choisir un argument décisif pour un vrai/faux.",
    items: [
      { id: "2025-j2-ex3-1", label: "Affirmation 1", question: "La suite (1+5ⁿ)/(2+3ⁿ) converge-t-elle vers 5/3 ?", notion: "Croissance exponentielle", recognition: "les exposants n interdisent de raisonner comme sur un quotient de fonctions affines", reasoning: "Les termes 5ⁿ et 3ⁿ dominent les constantes ; le quotient est équivalent à (5/3)ⁿ, qui tend vers +∞.", calculations: ["uₙ∼5ⁿ/3ⁿ=(5/3)ⁿ→+∞"], redaction: "La suite ne possède pas la limite finie annoncée.", result: "Affirmation fausse.", commonError: "Lire 5ⁿ et 3ⁿ comme 5n et 3n, ou appliquer le rapport 5/3 comme limite." },
      { id: "2025-j2-ex3-2", label: "Affirmation 2", question: "Prouver wₙ≥n.", notion: "Récurrence", recognition: "la relation permet de propager une minoration", reasoning: "À l’indice 0 l’inégalité est vraie. Si wₙ≥n, alors wₙ₊₁=3wₙ−2n+3≥n+3≥n+1.", calculations: ["w₀=0≥0", "wₙ₊₁≥n+3≥n+1"], redaction: "L’initialisation et l’hérédité établissent la propriété pour tout n.", result: "Affirmation vraie.", commonError: "Vérifier quelques termes sans démonstration générale." },
      { id: "2025-j2-ex3-3", label: "Affirmation 3", question: "La courbe est-elle convexe sur tout son domaine ?", notion: "Convexité graphique", recognition: "une courbe convexe reste au-dessus de ses tangentes", reasoning: "La tangente en A traverse la courbe : sur une partie du domaine, la courbe se situe sous cette tangente. Cela exclut la convexité globale.", redaction: "Le graphique fournit directement un contre-exemple à la propriété des tangentes.", result: "Affirmation fausse.", commonError: "Confondre fonction croissante et fonction convexe." },
      { id: "2025-j2-ex3-4", label: "Affirmation 4", question: "Justifier ln(x)−x+1≤0.", notion: "Inégalité classique du logarithme", recognition: "ln est concave et sa tangente en 1 a pour équation y=x−1", reasoning: "Une fonction concave est sous ses tangentes ; on peut aussi étudier φ(x)=ln x−x+1, maximale en 1.", calculations: ["φ′(x)=1/x−1 ; φ(1)=0"], redaction: "Le maximum de φ sur ]0;+∞[ est 0.", result: "Affirmation vraie, avec égalité seulement pour x=1.", commonError: "Oublier que l’énoncé suppose x>0." },
    ],
  },
  {
    id: "2025-j2-ex4", title: "Exercice 4 — freinage d’un chariot", points: "6 points officiels", difficulty: "Soutenue",
    topics: "Lecture graphique, équation différentielle, exponentielle, variations, intégration par parties et modélisation.",
    skill: "Passer de la vitesse à la distance et interpréter les unités.",
    items: [
      { id: "2025-j2-ex4-a", label: "Partie A", question: "Lire le temps, la longueur minimale et la vitesse sur le graphique.", notion: "Lecture graphique et dérivée", recognition: "d′ est la vitesse instantanée et l’asymptote donne la distance limite", reasoning: "La lecture donne environ 2 s pour 15 m, une asymptote vers 23 m et une pente de tangente proche de 1 au point d’abscisse 4,7.", redaction: "La précision reste celle permise par la figure, comme demandé.", result: "Environ 2 s ; environ 23 m ; d′(4,7)≈1 m·s⁻¹.", commonError: "Donner d(4,7) au lieu de la pente d′(4,7)." },
      { id: "2025-j2-ex4-b1", label: "Partie B · question 1", question: "Résoudre l’équation différentielle de la vitesse.", notion: "Équation différentielle linéaire", recognition: "la solution générale est la somme d’une solution homogène et de la solution particulière donnée", reasoning: "Les solutions homogènes sont Ce^(−0,6t). Comme g(t)=te^(−0,6t) vérifie l’équation complète, v(t)=(C+t)e^(−0,6t), puis v(0)=12 fixe C.", calculations: ["g′+0,6g=e^(−0,6t)", "v(t)=(12+t)e^(−0,6t)"], redaction: "La condition initiale représente la vitesse d’entrée dans la zone.", result: "v(t)=(12+t)e^(−0,6t) m·s⁻¹.", commonError: "Oublier la solution particulière te^(−0,6t)." },
      { id: "2025-j2-ex4-b23", label: "Partie B · questions 2 et 3", question: "Étudier la vitesse et trouver le déclenchement.", notion: "Dérivée, limite et théorème des valeurs intermédiaires", recognition: "le facteur exponentiel est positif", reasoning: "v′(t)=(−6,2−0,6t)e^(−0,6t)<0. La vitesse décroît continûment de 12 vers 0, donc v(t)=1 possède une unique solution.", calculations: ["α≈4,6915 s, soit 4,7 s au dixième"], redaction: "Le dispositif se déclenche dès que v≤1, donc à partir de l’unique instant α.", result: "Le système entre en action après environ 4,7 secondes.", commonError: "Arrondir α avant d’avoir justifié son unicité." },
      { id: "2025-j2-ex4-c1", label: "Partie C · question 1", question: "Exprimer la distance parcourue.", notion: "Intégration par parties", recognition: "d(t) est l’intégrale de la vitesse", reasoning: "On intègre 12e^(−0,6x) puis xe^(−0,6x) par parties, et on utilise d(0)=0.", calculations: ["d(t)=e^(−0,6t)(−5t/3−205/9)+205/9"], redaction: "La formule a l’unité du mètre et tend vers 205/9.", result: "d(t)=e^(−0,6t)(−5t/3−205/9)+205/9.", commonError: "Oublier la borne 0 et donc la constante 205/9." },
      { id: "2025-j2-ex4-c2", label: "Partie C · question 2", question: "Calculer la distance au déclenchement.", notion: "Évaluation numérique d’un modèle", recognition: "on réutilise l’instant α défini par v(α)=1", reasoning: "On conserve assez de décimales pour α avant de l’insérer dans d.", calculations: ["d(4,691499…)=20,944692…"], redaction: "L’arrondi au centième est effectué seulement à la fin.", result: "Le chariot parcourt environ 20,94 m avant le déclenchement.", commonError: "Utiliser α=4,7 trop tôt et perdre la précision demandée." },
    ],
  },
] as const;
