import type { ExamCorrectionExercise } from "@/components/marketing/OfficialExamCorrection";

export const premiere2026Pdf = "https://www.education.gouv.fr/sites/default/files/document/baccalaureat-general-2026-mathematiques-epreuve-anticipee-pour-les-candidats-avec-enseignements-de.pdf";

export const premiere2026Exercises: readonly ExamCorrectionExercise[] = [
  {
    id: "qcm", title: "Première partie — automatismes, 8 QCM", points: "6 points officiels", topics: "Développement, lecture graphique, pourcentages, ordre de grandeur, conversion d’unités, fonction du second degré et puissances.", difficulty: "Accessible", skill: "Produire une réponse courte et fiable sans calculatrice.",
    items: [
      { id: "q1", label: "QCM · question 1", question: "Développer le carré d’une expression affine.", notion: "Identité remarquable", recognition: "(a−b)²=a²−2ab+b²", reasoning: "On applique l’identité à 3x et 2.", calculations: ["(3x−2)²=9x²−12x+4"], redaction: "Le terme du milieu contient le facteur 2 : −2×3x×2=−12x.", result: "Réponse c : 9x²−12x+4.", commonError: "Écrire seulement 9x²−4 et oublier le double produit.", },
      { id: "q2", label: "QCM · question 2", question: "Identifier l’équation de la droite représentée.", notion: "Fonction affine", recognition: "la droite coupe l’axe des ordonnées en 2 et descend d’une unité quand x augmente d’une unité", reasoning: "Son ordonnée à l’origine est 2 et son coefficient directeur est −1.", calculations: ["y=−x+2"], redaction: "La lecture de deux points de la grille suffit à vérifier la pente et l’ordonnée à l’origine.", result: "Réponse c : y=−x+2.", commonError: "Choisir une pente −2 à partir d’une lecture sur des échelles différentes.", },
      { id: "q3", label: "QCM · question 3", question: "Retrouver l’effectif d’une classe à partir de 75 % et de 9 élèves restants.", notion: "Pourcentage", recognition: "les élèves de latin représentent les 25 % complémentaires", reasoning: "Si 25 % de la classe correspondent à 9 élèves, l’effectif total vaut 9/0,25.", calculations: ["N=9/0,25=36"], redaction: "Les 75 % en grec laissent 25 % en latin.", result: "Réponse d : 36 élèves.", commonError: "Calculer 75 % de 9 alors que 9 représente la partie complémentaire.", },
      { id: "q4", label: "QCM · question 4", question: "Traduire une hausse de 15 % en coefficient multiplicateur.", notion: "Évolution en pourcentage", recognition: "une hausse de t % utilise 1+t/100", reasoning: "On conserve 100 % du prix et on ajoute 15 %.", calculations: ["1+15/100=1,15"], redaction: "Multiplier par 1,15 produit bien un prix supérieur de 15 %.", result: "Réponse b : 1,15.", commonError: "Multiplier par 0,15, qui calcule seulement le montant de l’augmentation.", },
      { id: "q5", label: "QCM · question 5", question: "Choisir l’ordre de grandeur de 150 000/3 200.", notion: "Ordre de grandeur", recognition: "3 200 est proche de 3 000 et 150 000/3 000 vaut 50", reasoning: "Le quotient exact est 46,875, donc la proposition la plus proche est 50.", calculations: ["150 000/3 200=46,875"], redaction: "Un encadrement 3 000×50=150 000 rend déjà le bon ordre de grandeur visible.", result: "Réponse b : 50.", commonError: "Perdre un zéro et choisir 5 ou 500.", },
      { id: "q6", label: "QCM · question 6", question: "Calculer un nombre d’images par seconde.", notion: "Conversion d’unités et quotient", recognition: "1 min 40 s doit d’abord être converti en 100 secondes", reasoning: "Le débit moyen est le nombre total d’images divisé par la durée en secondes.", calculations: ["1 min 40 s=100 s", "2 400/100=24"], redaction: "L’unité finale est image par seconde.", result: "Réponse b : 24 images/seconde.", commonError: "Transformer 1 min 40 s en 140 secondes.", },
      { id: "q7", label: "QCM · question 7", question: "Repérer quel point appartient à la courbe de f(x)=0,5(x−3)²+10.", notion: "Image d’un réel", recognition: "un point (a;b) appartient à la courbe si b=f(a)", reasoning: "La forme canonique donne immédiatement f(3)=10.", calculations: ["f(3)=0,5×0²+10=10"], redaction: "Le point d’abscisse 3 et d’ordonnée 10 vérifie l’équation de la courbe.", result: "Réponse c : C(3;10).", commonError: "Croire que le sommet a pour ordonnée 10,5 à cause du coefficient 0,5.", },
      { id: "q8", label: "QCM · question 8", question: "Simplifier un quotient de puissances de dix.", notion: "Règles sur les puissances", recognition: "on additionne les exposants dans un produit, on les multiplie pour une puissance de puissance, puis on soustrait au quotient", reasoning: "L’exposant total du numérateur est 201−4 et celui du dénominateur est 2×100.", calculations: ["A=10^(201−4−200)=10^(−3)=0,001"], redaction: "Un exposant −3 correspond à déplacer la virgule de trois rangs vers la gauche.", result: "Réponse c : 0,001.", commonError: "Oublier que (10²)^100=10^200.", },
    ],
  },
  {
    id: "ex1", title: "Exercice 1 — location de bicyclettes", points: "5 points officiels", topics: "Arbre pondéré, intersection, probabilité totale et conditionnement.", difficulty: "Accessible", skill: "Compléter un arbre à partir d’informations directes et retrouver une branche inconnue.",
    items: [
      { id: "ex1-12", label: "Questions 1 et 2", question: "Compléter l’arbre et donner P(A).", notion: "Arbre pondéré", recognition: "60 % choisissent un vélo traditionnel et 25 % d’entre eux une assurance", reasoning: "On inscrit les probabilités et leurs complémentaires sur les branches. La probabilité de A est donnée pour l’ensemble des clients.", calculations: ["P(T)=0,60 ; P(non T)=0,40", "P(A|T)=0,25 ; P(non A|T)=0,75", "P(A)=0,20"], redaction: "Les branches issues d’un même nœud doivent toujours totaliser 1.", result: "P(A)=0,20.", commonError: "Placer 0,20 comme probabilité conditionnelle sur chacune des deux branches.", },
      { id: "ex1-34", label: "Questions 3 et 4", question: "Calculer les deux intersections qui conduisent à une assurance.", notion: "Produit sur une branche et probabilité totale", recognition: "T∩A se lit sur un chemin complet, puis A se décompose en deux chemins disjoints", reasoning: "On multiplie d’abord 0,60 et 0,25. Ensuite on soustrait cette part à P(A).", calculations: ["P(T∩A)=0,60×0,25=0,15", "P(non T∩A)=0,20−0,15=0,05"], redaction: "Les événements T∩A et non T∩A forment une partition de A.", result: "P(T∩A)=0,15 et P(non T∩A)=0,05.", commonError: "Soustraire 0,15 à P(non T)=0,40 au lieu de le soustraire à P(A).", },
      { id: "ex1-5", label: "Question 5", question: "Calculer la probabilité d’assurance sachant que le vélo est électrique.", notion: "Probabilité conditionnelle", recognition: "vélo électrique correspond à non T", reasoning: "On divise la probabilité de l’intersection non T∩A par P(non T).", calculations: ["P(A|non T)=0,05/0,40=5/40=1/8"], redaction: "Parmi les clients ayant loué un vélo électrique, un huitième a pris une assurance.", result: "P(A|non T)=1/8.", commonError: "Donner 0,05, qui est une probabilité conjointe et non conditionnelle.", },
    ],
  },
  {
    id: "ex2", title: "Exercice 2 — trois vrai/faux", points: "5 points officiels", topics: "Second degré, suite géométrique et tangente à l’exponentielle.", difficulty: "Intermédiaire", skill: "Justifier une affirmation universelle avec un discriminant, un quotient ou une équation de tangente.",
    items: [
      { id: "ex2-1", label: "Affirmation 1", question: "L’équation x²+x−u²=0 a-t-elle toujours deux solutions réelles distinctes ?", notion: "Discriminant", recognition: "le paramètre u intervient au carré", reasoning: "Le discriminant vaut 1−4×1×(−u²)=1+4u², strictement positif pour tout réel u.", calculations: ["Δ=1+4u²>0"], redaction: "Un discriminant strictement positif assure exactement deux solutions réelles distinctes.", result: "Affirmation vraie pour tout réel u.", commonError: "Écrire Δ=1−4u² et fabriquer des cas inexistants.", },
      { id: "ex2-2", label: "Affirmation 2", question: "La suite uₙ=2^(−n) est-elle géométrique de raison 1/2 ?", notion: "Suite géométrique", recognition: "2^(−n)=(1/2)^n", reasoning: "Le quotient de deux termes consécutifs est constant.", calculations: ["uₙ₊₁/uₙ=2^(−n−1)/2^(−n)=2^(−1)=1/2"], redaction: "La relation uₙ₊₁=(1/2)uₙ vaut pour tout n.", result: "Affirmation vraie.", commonError: "Lire l’exposant −n comme une raison −2.", },
      { id: "ex2-3", label: "Affirmation 3", question: "Le point A(3;3) appartient-il à la tangente en 0 de f(x)=eˣ−1 ?", notion: "Équation de tangente", recognition: "T : y=f(0)+f′(0)(x−0)", reasoning: "On a f(0)=0 et f′(x)=eˣ, donc f′(0)=1.", calculations: ["T : y=x", "pour x=3, y=3"], redaction: "Les coordonnées de A vérifient l’équation de la tangente.", result: "Affirmation vraie.", commonError: "Tester A sur la courbe de f au lieu de le tester sur la tangente.", },
    ],
  },
  {
    id: "ex3", title: "Exercice 3 — produit scalaire dans le plan", points: "4 points officiels", topics: "Coordonnées de vecteurs, normes, produit scalaire et angle.", difficulty: "Intermédiaire", skill: "Traduire une condition angulaire en équation puis vérifier une solution exacte.",
    items: [
      { id: "ex3-12", label: "Questions 1 et 2", question: "Calculer les vecteurs KP, KM et leurs normes.", notion: "Coordonnées et norme", recognition: "les coordonnées d’un vecteur sont arrivée moins départ", reasoning: "On soustrait les coordonnées de K à celles de P puis de M.", calculations: ["KP=(4−1;0−0)=(3;0), donc ‖KP‖=3", "KM=(x−1;3), donc ‖KM‖=√((x−1)²+9)"], redaction: "La norme est la racine carrée de la somme des carrés des coordonnées.", result: "KP=(3;0), ‖KP‖=3 ; KM=(x−1;3), ‖KM‖=√((x−1)²+9).", commonError: "Soustraire dans des sens différents pour les deux coordonnées d’un même vecteur.", },
      { id: "ex3-3", label: "Question 3", question: "Exprimer le produit scalaire KP·KM.", notion: "Produit scalaire en coordonnées", recognition: "on multiplie les coordonnées de même rang puis on additionne", reasoning: "La seconde coordonnée de KP est nulle.", calculations: ["KP·KM=3(x−1)+0×3=3x−3"], redaction: "Le calcul ne nécessite ni norme ni angle à cette étape.", result: "KP·KM=3x−3.", commonError: "Multiplier les normes, ce qui ne donne le produit scalaire qu’après prise en compte du cosinus.", },
      { id: "ex3-4", label: "Question 4", question: "Traduire l’angle PKM=π/3 en une équation.", notion: "Formule du produit scalaire", recognition: "les deux vecteurs partent du sommet K", reasoning: "On égalise KP·KM et ‖KP‖‖KM‖cos(π/3), avec cos(π/3)=1/2.", calculations: ["3x−3=(3/2)√((x−1)²+9)", "√((x−1)²+9)=2x−2"], redaction: "L’égalité implique en particulier x≥1, ce qui est cohérent avec un second membre non négatif.", result: "x vérifie l’équation √((x−1)²+9)=2x−2.", commonError: "Utiliser les vecteurs KP et MK, orientés en sens opposés, et changer le signe de l’angle.", },
      { id: "ex3-5", label: "Question 5", question: "Vérifier que 1+√3 est solution.", notion: "Substitution exacte", recognition: "il suffit de comparer les deux membres sans résoudre toute l’équation", reasoning: "Pour x=1+√3, x−1=√3.", calculations: ["membre gauche=√(3+9)=√12=2√3", "membre droit=2(1+√3)−2=2√3"], redaction: "Les deux membres sont égaux et le radical est bien défini.", result: "1+√3 est solution de l’équation.", commonError: "Remplacer √12 par 6 au lieu de 2√3.", },
    ],
  },
] as const;
