import type { ExamCorrectionExercise } from "@/components/marketing/OfficialExamCorrection";

export const bac2024J1Pdf = "https://eduscol.education.gouv.fr/sites/default/files/document/24-matj1me1v1-0pdf-106221.pdf";
export const bac2024J2Pdf = "https://eduscol.education.gouv.fr/sites/default/files/document/24-matj2me2v1pdf-106281.pdf";

export const bac2024J1Exercises: readonly ExamCorrectionExercise[] = [
  {
    id: "2024-j1-ex1", title: "Exercice 1 — vrai/faux fonctions et suites", points: "4 points officiels", difficulty: "Intermédiaire", topics: "Exponentielle, équation différentielle, limites et encadrement de suites.", skill: "Produire une preuve ou un contre-exemple décisif.",
    items: [
      { id: "2024-j1-ex1-12", label: "Affirmations 1 et 2", question: "Étudier f(x)=5xe^(−x) et vérifier une équation différentielle.", notion: "Limite exponentielle et dérivation", recognition: "une asymptote horizontale se lit sur une limite et une solution d’équation se vérifie par substitution", reasoning: "En +∞, xe^(−x) tend vers 0. De plus f′(x)=5(1−x)e^(−x), donc f′+f=5e^(−x).", calculations: ["lim f(x)=0 lorsque x→+∞", "f′(x)+f(x)=5e^(−x)"], redaction: "Les deux propriétés annoncées sont vérifiées sur le domaine concerné.", result: "Affirmations 1 et 2 vraies.", commonError: "Résoudre toute l’équation différentielle alors qu’une simple vérification suffit." },
      { id: "2024-j1-ex1-34", label: "Affirmations 3 et 4", question: "Que peut-on déduire de uₙ≤vₙ≤wₙ ?", notion: "Encadrement de suites", recognition: "les deux suites encadrantes n’ont pas la même limite", reasoning: "L’encadrement entre −1 et 1 n’impose pas la convergence : vₙ=(−1)ⁿ fournit un contre-exemple avec uₙ=−1 et wₙ=1. Si u est croissante et w décroissante, u₀≤uₙ≤vₙ≤wₙ≤w₀.", calculations: ["uₙ=−1 ; vₙ=(−1)ⁿ ; wₙ=1"], redaction: "Le théorème des gendarmes ne s’applique que lorsque les deux bornes convergent vers la même limite.", result: "Affirmation 3 fausse ; affirmation 4 vraie.", commonError: "Appliquer le théorème des gendarmes avec deux limites différentes." },
    ],
  },
  {
    id: "2024-j1-ex2", title: "Exercice 2 — satisfaction et livraison", points: "5 points officiels", difficulty: "Intermédiaire", topics: "Probabilités conditionnelles, loi binomiale, somme de variables indépendantes et Bienaymé-Tchebychev.", skill: "Passer d’un arbre à plusieurs modèles de variables aléatoires.",
    items: [
      { id: "2024-j1-ex2-14", label: "Questions 1 à 4", question: "Compléter l’arbre d’achat et calculer les probabilités de satisfaction.", notion: "Probabilités totales et conditionnelles", recognition: "internet, magasin et grande surface forment une partition", reasoning: "On pondère 0,60/0,30/0,10 par 0,75/0,90/0,80. La somme des trois chemins satisfaits vaut 0,80.", calculations: ["P(I∩S)=0,60×0,75=0,45", "P(S)=0,45+0,27+0,08=0,80", "P(I|S)=0,45/0,80=0,5625≈0,563"], redaction: "La dernière probabilité est arrondie au millième.", result: "P(S)=0,80 et P(I|S)≈0,563.", commonError: "Confondre P(I|S) avec P(S|I)=0,75." },
      { id: "2024-j1-ex2-56", label: "Questions 5 et 6", question: "Étudier un échantillon de clients satisfaits puis dimensionner un sondage.", notion: "Loi binomiale et événement contraire", recognition: "les tirages sont assimilés indépendants avec p=0,8", reasoning: "Pour 30 clients, X suit B(30;0,8). Pour obtenir au moins un insatisfait avec une probabilité supérieure à 0,99, on travaille sur l’événement contraire : tous satisfaits.", calculations: ["P(X≥25)≈0,428", "1−0,8ⁿ>0,99 ⇔ n>ln(0,01)/ln(0,8)≈20,64"], redaction: "Le plus petit entier admissible est retenu après résolution de l’inéquation stricte.", result: "P(X≥25)≈0,428 et il faut au moins 21 clients.", commonError: "Calculer P(X=25) au lieu de P(X≥25)." },
      { id: "2024-j1-ex2-7", label: "Question 7", question: "Étudier le temps total de livraison T=T₁+T₂.", notion: "Somme de variables indépendantes", recognition: "les espérances s’ajoutent et l’indépendance permet d’ajouter les variances", reasoning: "E(T)=4+3 et V(T)=2+1. Comme T prend des valeurs entières, 5≤T≤9 équivaut à |T−7|<3 ; Bienaymé-Tchebychev donne la minoration.", calculations: ["E(T)=7 jours ; V(T)=3 jours²", "P(|T−7|<3)≥1−3/9=2/3"], redaction: "La borne garantit au moins deux chances sur trois de recevoir le téléviseur entre 5 et 9 jours inclus.", result: "E(T)=7, V(T)=3 et P(5≤T≤9)≥2/3.", commonError: "Additionner les écarts-types ou oublier que T est à valeurs entières." },
    ],
  },
  {
    id: "2024-j1-ex3", title: "Exercice 3 — tétraèdre et distance", points: "5 points officiels", difficulty: "Intermédiaire", topics: "Plans, projection orthogonale, produit scalaire, aire, volume et distance.", skill: "Réutiliser un même volume avec deux bases différentes.",
    items: [
      { id: "2024-j1-ex3-12", label: "Questions 1 et 2", question: "Déterminer le plan (CAD) et le projeté de B.", notion: "Vecteur normal et projection", recognition: "un projeté appartient au plan et la droite de projection est normale au plan", reasoning: "Le vecteur (1;−1;0) est orthogonal à CA et CD ; le plan passant par D a donc pour équation x−y=0. Sur la droite donnée, l’intersection impose t=1.", calculations: ["H=(5/2;5/2;0)", "BH=(5/2;−5/2;0)=(5/2)(1;−1;0)"], redaction: "H appartient à (CAD) et BH est normal à ce plan.", result: "(CAD): x−y=0 et H est le projeté orthogonal de B.", commonError: "Vérifier seulement H∈(CAD) sans établir l’orthogonalité." },
      { id: "2024-j1-ex3-34", label: "Questions 3 et 4", question: "Calculer l’aire de ABH puis le volume du tétraèdre ABCH.", notion: "Produit scalaire, aire et volume", recognition: "ABH est rectangle en H et CO est perpendiculaire au plan z=0", reasoning: "AH et BH ont chacun pour longueur 5/√2 et leur produit scalaire est nul. La base ABH a donc une aire 25/4 ; la hauteur CO vaut 10.", calculations: ["A(ABH)=1/2×(5/√2)²=25/4", "V(ABCH)=1/3×25/4×10=125/6"], redaction: "Le plan (ABH) est z=0, d’où la hauteur issue de C.", result: "A(ABH)=25/4 et V=125/6 unités cubes.", commonError: "Oublier le facteur 1/3 dans le volume du tétraèdre." },
      { id: "2024-j1-ex3-5", label: "Question 5", question: "Déduire la distance de H au plan (ABC).", notion: "Volume et distance point-plan", recognition: "le même tétraèdre peut être calculé avec la base ABC", reasoning: "ABC est rectangle en B, avec AB=5 et BC=5√5, donc son aire vaut 25√5/2. Si d est la hauteur issue de H, 125/6=(1/3)(25√5/2)d.", calculations: ["d=√5"], redaction: "La hauteur relative à la base ABC est précisément la distance de H au plan (ABC).", result: "d(H,(ABC))=√5.", commonError: "Réutiliser CO=10, qui correspond à une autre base." },
    ],
  },
  {
    id: "2024-j1-ex4", title: "Exercice 4 — logarithme, fonction auxiliaire et aire", points: "6 points officiels", difficulty: "Soutenue", topics: "Limites, dérivation, convexité, logarithme, fonction auxiliaire et intégrale.", skill: "Faire circuler une information entre deux fonctions puis calculer une aire.",
    items: [
      { id: "2024-j1-ex4-a1", label: "Partie A · question 1", question: "Étudier f(x)=x−2+(1/2)ln x.", notion: "Limites, variations et convexité", recognition: "sur x>0, f′ est positive et f″ négative", reasoning: "Le logarithme impose la limite −∞ en 0+, tandis que le terme x entraîne +∞ en +∞. La dérivée (2x+1)/(2x) est positive et la dérivée seconde vaut −1/(2x²).", calculations: ["f′(x)=(2x+1)/(2x)>0", "f″(x)=−1/(2x²)<0"], redaction: "f est strictement croissante et concave sur ]0;+∞[.", result: "Limites −∞ et +∞ ; f croissante et concave.", commonError: "Déclarer f convexe parce qu’elle est croissante." },
      { id: "2024-j1-ex4-a2", label: "Partie A · question 2", question: "Établir l’existence, l’unicité et le rôle de α.", notion: "Théorème des valeurs intermédiaires", recognition: "continuité et stricte croissance donnent l’unicité", reasoning: "f(1)=−1 et f(2)=(1/2)ln2>0, donc α∈[1;2]. Le signe suit les variations. L’égalité f(α)=0 se réarrange.", calculations: ["α≈1,72685", "ln α=2(2−α)"], redaction: "f est négative avant α, nulle en α et positive après α.", result: "Une unique racine α∈[1;2], avec ln α=2(2−α).", commonError: "Utiliser le TVI sans justifier l’unicité." },
      { id: "2024-j1-ex4-b", label: "Partie B", question: "Étudier g grâce à f(1/x).", notion: "Dérivation composée et variations", recognition: "g′(x)=xf(1/x) et x reste positif", reasoning: "La dérivation donne 1−2x−(x/2)ln x. Le signe de f(1/x) change lorsque 1/x=α, soit x=1/α.", calculations: ["g′(x)=1−2x−(x/2)ln x=xf(1/x)"], redaction: "g croît sur ]0;1/α], puis décroît sur [1/α;1].", result: "g atteint son maximum en x=1/α.", commonError: "Oublier que l’inversion x↦1/x renverse l’ordre." },
      { id: "2024-j1-ex4-c", label: "Partie C", question: "Calculer l’aire entre C_g et la parabole.", notion: "Position relative et intégration par parties", recognition: "g(x)−P(x)=−(1/4)x²ln x≥0 sur ]0;1]", reasoning: "La courbe C_g est au-dessus de P. Une intégration par parties de x²ln x entre 1/α et 1, suivie de ln α=2(2−α), donne l’expression demandée.", calculations: ["∫₁⁄ₐ¹x²ln x dx=(−α³−6α+13)/(9α³)", "A=−1/4∫₁⁄ₐ¹x²ln x dx=(α³+6α−13)/(36α³)"], redaction: "L’intégrande de l’aire est bien non négatif sur les bornes considérées.", result: "A=(α³+6α−13)/(36α³) unité d’aire.", commonError: "Intégrer P−g et obtenir une valeur négative." },
    ],
  },
] as const;

export const bac2024J2Exercises: readonly ExamCorrectionExercise[] = [
  {
    id: "2024-j2-ex1", title: "Exercice 1 — réussite à un examen", points: "5 points officiels", difficulty: "Intermédiaire", topics: "Probabilités conditionnelles, loi binomiale, espérance, variance et Bienaymé-Tchebychev.", skill: "Identifier un paramètre inconnu puis interpréter une moyenne.",
    items: [
      { id: "2024-j2-ex1-13", label: "Questions 1 à 3", question: "Retrouver le taux de réussite et conditionner par la réponse “oui”.", notion: "Probabilités totales et Bayes", recognition: "la probabilité observée de Q se décompose selon réussite ou échec", reasoning: "On connaît P(Q)=0,917, P(Q|R)=0,98 et P(Q|non R)=0,35. L’équation totale détermine x=P(R), puis la formule conditionnelle répond à la question 3.", calculations: ["0,917=0,98x+0,35(1−x) ⇒ x=0,9", "P(R|Q)=0,98×0,9/0,917≈0,962"], redaction: "Environ 96,2 % des étudiants ayant répondu oui ont effectivement réussi.", result: "P(R)=0,9 et P(R|Q)≈0,962.", commonError: "Utiliser 0,65 comme P(Q|non R), alors qu’il s’agit de P(non Q|non R)." },
      { id: "2024-j2-ex1-4", label: "Question 4", question: "Fixer une note seuil pour récompenser environ 65 % des étudiants.", notion: "Loi binomiale et probabilité cumulée", recognition: "“à partir de” appelle une probabilité de queue P(N≥k)", reasoning: "Pour N suivant B(20;0,615), le seuil 12 donne la proportion la plus directement visée par l’énoncé.", calculations: ["P(N≥12)≈0,648682, soit 64,9 %"], redaction: "La valeur de 65 % est atteinte à l’arrondi près, le modèle étant discret.", result: "La récompense est attribuée à partir de 12/20.", commonError: "Chercher P(N=12) au lieu de la proportion obtenant au moins 12." },
      { id: "2024-j2-ex1-56", label: "Questions 5 et 6", question: "Étudier la somme puis la moyenne des notes de dix étudiants.", notion: "Somme et transformation de variables", recognition: "les dix variables indépendantes ont la même loi", reasoning: "Les espérances et, grâce à l’indépendance, les variances s’ajoutent. Pour M=S/10, la variance est multipliée par 1/100. Tchebychev s’applique avec un écart de 2.", calculations: ["E(S)=123 ; V(S)=47,355", "E(M)=12,3 ; V(M)=0,47355", "P(|M−12,3|<2)≥1−0,47355/4≈0,882≥0,80"], redaction: "M représente la moyenne sur 20 des dix notes.", result: "La probabilité d’une moyenne dans ]10,3;14,3[ est garantie à au moins 80 %.", commonError: "Diviser la variance de S par 10 au lieu de 10²." },
    ],
  },
  {
    id: "2024-j2-ex2", title: "Exercice 2 — chlore d’une piscine", points: "5 points officiels", difficulty: "Intermédiaire", topics: "Suite arithmético-géométrique, récurrence, Python et équation différentielle.", skill: "Interpréter et comparer un modèle discret et un modèle continu.",
    items: [
      { id: "2024-j2-ex2-a1", label: "Partie A · question 1", question: "Convertir 15 g de chlore en hausse de concentration.", notion: "Proportion et unités", recognition: "15 g=15 000 mg et 50 m³=50 000 L", reasoning: "On divise la masse ajoutée par le volume total.", calculations: ["15 000/50 000=0,3 mg·L⁻¹"], redaction: "La conversion des deux grandeurs précède le quotient.", result: "L’ajout augmente le taux de 0,3 mg·L⁻¹.", commonError: "Mélanger grammes et milligrammes." },
      { id: "2024-j2-ex2-a25", label: "Partie A · questions 2 à 5", question: "Étudier la suite des taux et programmer le seuil d’alerte.", notion: "Suite récurrente et boucle while", recognition: "la fonction x↦0,92x+0,3 est croissante", reasoning: "Une récurrence établit vₙ≤vₙ₊₁≤4. La suite croissante majorée converge vers L vérifiant L=0,92L+0,3, soit 3,75. L’algorithme répète la relation tant que v≤s.", calculations: ["while v <= s:", "n=n+1 ; v=0.92*v+0.3", "alerte_chlore(3)=17"], redaction: "Le seuil de 3 mg·L⁻¹ est dépassé au 17e jour ; la limite 3,75 n’est pas conforme à la plage 1–3.", result: "vₙ→3,75 et le premier indice avec vₙ>3 est 17.", commonError: "Répondre que 3,75 reste conforme parce que la suite est majorée par 4." },
      { id: "2024-j2-ex2-b", label: "Partie B", question: "Calibrer le modèle continu pour une stabilisation à 2 mg·L⁻¹.", notion: "Équation différentielle y′=ay+b", recognition: "la valeur d’équilibre est q/4", reasoning: "La solution générale est Ce^(−0,08x)+q/4. Une limite égale à 2 impose q=8 g par jour, puis f(0)=0,7 impose C=−1,3.", calculations: ["lim f=q/4", "q/4=2 ⇒ q=8", "C+2=0,7 ⇒ C=−1,3"], redaction: "Les unités de q restent des grammes ajoutés chaque jour.", result: "f(x)=−1,3e^(−0,08x)+2 avec q=8 g.", commonError: "Identifier q/50 comme limite au lieu de tenir compte du coefficient 0,08." },
    ],
  },
  {
    id: "2024-j2-ex3", title: "Exercice 3 — fonction et distance minimale", points: "6 points officiels", difficulty: "Soutenue", topics: "Logarithme, limites, variations, convexité, optimisation et tangente.", skill: "Transformer une question géométrique en étude de fonction.",
    items: [
      { id: "2024-j2-ex3-a", label: "Partie A", question: "Lire f(−1), f′(−1), la convexité et une racine.", notion: "Lecture graphique", recognition: "la pente de la tangente passant par A(0;−1) se calcule avec B(−1;−2)", reasoning: "La courbe change de courbure : elle n’est pas convexe sur tout son domaine. Elle semble couper l’axe une seule fois, près de 0,1.", calculations: ["f(−1)=−2 ; f′(−1)=1"], redaction: "La précision de la racine reste celle demandée par le graphique.", result: "f(−1)=−2, f′(−1)=1, non convexe globalement, une racine vers 0,1.", commonError: "Lire l’ordonnée du point A comme f(−1)." },
      { id: "2024-j2-ex3-b", label: "Partie B", question: "Mener l’étude complète de f(x)=x²+2x−1+ln(x+2).", notion: "Limites, dérivée et convexité", recognition: "le numérateur de f′ est un trinôme toujours positif", reasoning: "f tend vers −∞ en −2+ et vers +∞ en +∞. Le discriminant de 2x²+6x+5 vaut −4, donc f est strictement croissante et possède une unique racine. La dérivée seconde change une fois de signe.", calculations: ["f′(x)=(2x²+6x+5)/(x+2)>0", "α≈0,11785, donc α≈0,12", "f″(x)=2−1/(x+2)²=0 ⇔ x=−2+1/√2"], redaction: "f est négative avant α, puis positive ; le point d’inflexion a pour abscisse −2+1/√2.", result: "Une unique racine α≈0,12 et un unique point d’inflexion.", commonError: "Oublier que x+2>0 sur tout le domaine." },
      { id: "2024-j2-ex3-c12", label: "Partie C · questions 1 et 2", question: "Minimiser la distance JM sur la courbe du logarithme.", notion: "Distance au carré et variations", recognition: "minimiser JM revient à minimiser h=JM²", reasoning: "Pour M(x;ln(x+2)) et J(0;1), h=x²+[ln(x+2)−1]². Comme h′=2f/(x+2), h décroît avant α et croît après α.", calculations: ["h(x)=x²+[ln(x+2)−1]²"], redaction: "Le dénominateur x+2 est positif, donc h′ a le signe de f.", result: "La distance JM est minimale pour x=α.", commonError: "Minimiser directement une racine carrée et alourdir inutilement le calcul." },
      { id: "2024-j2-ex3-c3", label: "Partie C · question 3", question: "Prouver l’orthogonalité au point le plus proche.", notion: "Tangente et coefficient directeur", recognition: "l’équation f(α)=0 simplifie la pente de JMα", reasoning: "On obtient ln(α+2)=1−2α−α². La pente de la tangente à C_g vaut 1/(α+2), celle de JMα vaut [ln(α+2)−1]/α=−(α+2).", calculations: ["(1/(α+2))×(−(α+2))=−1"], redaction: "Le produit des coefficients directeurs vaut −1 dans un repère orthonormé.", result: "La tangente en Mα est perpendiculaire à (JMα).", commonError: "Utiliser la pente α/[ln(α+2)−1], qui correspond à l’inverse du quotient." },
    ],
  },
  {
    id: "2024-j2-ex4", title: "Exercice 4 — quatre affirmations de géométrie", points: "4 points officiels", difficulty: "Accessible", topics: "Équations de plans, coplanarité, intersection de droites et projection orthogonale.", skill: "Tester chaque affirmation par la condition la plus courte.",
    items: [
      { id: "2024-j2-ex4-1", label: "Affirmation 1", question: "A, C et D définissent-ils le plan annoncé ?", notion: "Équation cartésienne", recognition: "les trois points doivent vérifier l’équation et ne pas être alignés", reasoning: "La substitution de A, C et D donne zéro ; les vecteurs AC et AD ne sont pas colinéaires.", redaction: "Les trois points distincts non alignés déterminent bien ce plan.", result: "Affirmation vraie.", commonError: "Vérifier les points sans s’assurer qu’ils définissent un plan unique." },
      { id: "2024-j2-ex4-2", label: "Affirmation 2", question: "A, B, C et D sont-ils coplanaires ?", notion: "Appartenance à un plan", recognition: "le plan (ABC) est fourni dans la suite du sujet", reasoning: "D(0;0;4) ne vérifie pas x−y+2z−2=0 : le membre vaut 6.", redaction: "D n’appartient pas au plan défini par A, B et C.", result: "Affirmation fausse.", commonError: "Utiliser le plan de l’affirmation 1, qui est (ACD), pour conclure sur B." },
      { id: "2024-j2-ex4-3", label: "Affirmation 3", question: "Les droites (AC) et (BH) sont-elles sécantes ?", notion: "Droites paramétriques", recognition: "on cherche des paramètres distincts donnant le même point", reasoning: "A+tAC et B+sBH coïncident pour t=−5 et s=8.", calculations: ["A−5AC=(−8;−20;−5)=B+8BH"], redaction: "Un point commun suffit pour établir qu’elles sont sécantes.", result: "Affirmation vraie.", commonError: "Rejeter des paramètres négatifs alors que les objets sont des droites, pas des segments." },
      { id: "2024-j2-ex4-4", label: "Affirmation 4", question: "H est-il le projeté orthogonal de D ?", notion: "Projection orthogonale", recognition: "H doit appartenir au plan et DH être normal", reasoning: "H vérifie l’équation de (ABC), et DH=(−1;1;−2)=−(1;−1;2), colinéaire à un vecteur normal du plan.", redaction: "Les deux conditions de la projection sont satisfaites.", result: "Affirmation vraie.", commonError: "Vérifier l’orthogonalité sans l’appartenance de H au plan." },
    ],
  },
] as const;
