import type { ExamCorrectionExercise } from "@/components/marketing/OfficialExamCorrection";

export const terminaleJ1Pdf = "https://www.education.gouv.fr/sites/default/files/document/baccalaureat-general-2026-mathematiques-517598.pdf";
export const terminaleJ2Pdf = "https://www.education.gouv.fr/sites/default/files/document/baccalaureat-general-2026-mathematiques-jour-2-517817.pdf";

export const terminaleJ1Exercises: readonly ExamCorrectionExercise[] = [
  {
    id: "j1-ex1",
    title: "Exercice 1 — traversée en ferry",
    points: "5 points officiels",
    topics: "Probabilités conditionnelles, variables aléatoires, espérance, variance, moyenne d’échantillon et inégalité de Bienaymé-Tchebychev.",
    difficulty: "Intermédiaire",
    skill: "Traduire des données probabilistes puis raisonner sur une somme de variables indépendantes.",
    items: [
      {
        id: "j1-ex1-a12", label: "Partie A · questions 1 et 2", question: "Compléter l’arbre et calculer la probabilité de réserver véhicule et cabine.", notion: "Arbre pondéré et intersection", recognition: "une branche porte une probabilité conditionnelle et le chemin complet se calcule par produit", reasoning: "On place P(V)=0,30, P(C|V)=0,80 et leurs complémentaires. Le chemin V puis C donne l’intersection.", calculations: ["P(non V)=0,70 ; P(non C|V)=0,20", "P(V ∩ C)=0,30 × 0,80=0,24"], redaction: "La probabilité d’une cabine est donnée directement : P(C)=0,75. Sur la branche V, les poids sont 0,80 et 0,20 ; à la racine, 0,30 et 0,70.", result: "P(V ∩ C)=0,24, soit 24 %.", commonError: "Additionner les probabilités le long d’une branche au lieu de les multiplier.",
      },
      {
        id: "j1-ex1-a34", label: "Partie A · questions 3 et 4", question: "Calculer P(V|C) puis P(C|non V) et interpréter.", notion: "Probabilités conditionnelles", recognition: "on connaît une intersection et la probabilité de l’événement conditionnant", reasoning: "Pour la seconde valeur, on décompose C selon V et non V : P(non V ∩ C)=P(C)−P(V ∩ C).", calculations: ["P(V|C)=0,24/0,75=0,32", "P(non V ∩ C)=0,75−0,24=0,51", "P(C|non V)=0,51/0,70≈0,73"], redaction: "Par définition d’une probabilité conditionnelle, on divise l’intersection par la probabilité de la condition.", result: "P(V|C)=0,32 et P(C|non V)≈0,73 : environ 73 % des familles sans véhicule réservent une cabine.", commonError: "Inverser P(V|C) et P(C|V), qui ne répondent pas à la même question.",
      },
      {
        id: "j1-ex1-b1", label: "Partie B · question 1", question: "Vérifier l’espérance 96 et la variance 3 114 de X.", notion: "Loi d’une variable aléatoire", recognition: "l’espérance est la moyenne pondérée et la variance se calcule avec E(X²)−E(X)²", reasoning: "On utilise les quatre valeurs de la loi, sans oublier la valeur 0.", calculations: ["E(X)=70×0,06+100×0,51+170×0,24=96", "E(X²)=70²×0,06+100²×0,51+170²×0,24=12 330", "V(X)=12 330−96²=3 114"], redaction: "Les probabilités totalisent 1 ; on peut donc appliquer directement les formules de la loi finie.", result: "E(X)=96 € et V(X)=3 114 €².", commonError: "Donner une variance en euros : son unité est ici l’euro carré.",
      },
      {
        id: "j1-ex1-b2", label: "Partie B · question 2", question: "Modéliser la réduction de 40 %, puis calculer E(Z) et V(Z).", notion: "Transformation affine et indépendance", recognition: "payer 60 % du total revient à multiplier X+Y par 0,6", reasoning: "L’espérance est linéaire. Pour la variance, l’indépendance donne V(X+Y)=V(X)+V(Y), puis le facteur 0,6 est élevé au carré.", calculations: ["Z=0,6(X+Y)", "E(Z)=0,6(96+104)=120", "V(Z)=0,6²(3 114+1 686)=0,36×4 800=1 728"], redaction: "La remise de 40 % laisse 60 % du prix initial ; l’indépendance est utilisée uniquement pour additionner les variances.", result: "E(Z)=120 € et V(Z)=1 728 €².", commonError: "Multiplier la variance par 0,6 au lieu de 0,6².",
      },
      {
        id: "j1-ex1-b3", label: "Partie B · question 3", question: "Étudier la moyenne Mₙ et trouver le plus petit échantillon garanti à 85 %.", notion: "Moyenne de variables indépendantes et Bienaymé-Tchebychev", recognition: "la moyenne conserve l’espérance et divise la variance par n", reasoning: "L’intervalle ]114;126[ correspond à |Mₙ−120|<6. L’inégalité majore la probabilité complémentaire par V(Mₙ)/6².", calculations: ["E(Mₙ)=120 ; V(Mₙ)=1 728/n", "P(|Mₙ−120|≥6)≤(1 728/n)/36=48/n", "1−48/n≥0,85 ⇔ n≥320"], redaction: "Pour n=320, l’inégalité assure au moins 0,85 de probabilité d’obtenir une moyenne strictement comprise entre 114 € et 126 €.", result: "Le plus petit entier est n=320 familles.", commonError: "Présenter 320 comme une probabilité exacte : c’est une garantie issue d’une borne.",
      },
    ],
  },
  {
    id: "j1-ex2", title: "Exercice 2 — quatre affirmations", points: "4 points officiels", topics: "Géométrie dans l’espace, produit scalaire, angle et dénombrement.", difficulty: "Intermédiaire", skill: "Justifier une réponse vraie ou fausse par un calcul décisif.",
    items: [
      { id: "j1-ex2-1", label: "Affirmation 1", question: "Le plan est-il le plan médiateur de [AB] ?", notion: "Plan et droite orthogonaux", recognition: "le vecteur AB peut être comparé au vecteur normal du plan", reasoning: "AB=(−1;1;−5), exactement le vecteur normal du plan. Le milieu I=(2,5;0,5;−0,5) vérifie aussi l’équation.", calculations: ["−2,5+0,5−5(−0,5)−0,5=0"], redaction: "Comme AB est normal au plan et que le milieu de [AB] appartient au plan, les deux propriétés annoncées sont vérifiées.", result: "Affirmation vraie.", commonError: "Vérifier seulement l’orthogonalité sans contrôler que le milieu appartient au plan.", },
      { id: "j1-ex2-2", label: "Affirmation 2", question: "Les droites d et (AB) sont-elles sécantes ?", notion: "Représentations paramétriques", recognition: "un point commun doit satisfaire simultanément les trois coordonnées", reasoning: "Sur (AB), un point s’écrit (3−s;s;2−5s). L’égalité des x impose s=3−t, celle des y impose s=−1,5−t : ces deux égalités sont incompatibles.", calculations: ["3−t=−1,5−t donnerait 3=−1,5"], redaction: "Le système n’a aucune solution ; les droites ne possèdent donc aucun point commun.", result: "Affirmation fausse.", commonError: "Conclure après avoir égalé une seule coordonnée.", },
      { id: "j1-ex2-3", label: "Affirmation 3", question: "L’angle ACB vaut-il 70,5° au dixième ?", notion: "Produit scalaire et angle", recognition: "cos(ACB)=CA·CB/(‖CA‖‖CB‖)", reasoning: "Avec CA=(1,5;3;3) et CB=(0,5;4;−2), le produit scalaire vaut 6,75 et les deux normes valent 4,5.", calculations: ["cos(ACB)=6,75/(4,5×4,5)=1/3", "ACB=arccos(1/3)≈70,5288°"], redaction: "L’arrondi au dixième de degré est 70,5°.", result: "Affirmation vraie.", commonError: "Utiliser les vecteurs AC et CB, qui ne partent pas du même sommet.", },
      { id: "j1-ex2-4", label: "Affirmation 4", question: "Le code non ordonné de quatre symboles est-il plus facile à trouver ?", notion: "Arrangements et combinaisons", recognition: "l’ordre compte pour la porte A mais pas pour la porte B", reasoning: "Il y a 8×7×6 codes ordonnés de trois symboles et C(8,4) ensembles non ordonnés de quatre symboles.", calculations: ["N_A=336 ; P_A=1/336", "N_B=C(8,4)=70 ; P_B=1/70"], redaction: "Comme 1/70>1/336, le choix de Titouan a la probabilité de succès la plus élevée.", result: "Affirmation vraie.", commonError: "Compter 8⁴ codes pour la porte B alors que les symboles sont distincts et l’ordre indifférent.", },
    ],
  },
  {
    id: "j1-ex3", title: "Exercice 3 — chauffage et refroidissement", points: "6 points officiels", topics: "Équation différentielle, fonction exponentielle, suite récurrente, convergence et Python.", difficulty: "Intermédiaire", skill: "Passer d’un modèle continu à un modèle discret et interpréter chaque limite.",
    items: [
      { id: "j1-ex3-a12", label: "Partie A · questions 1 et 2", question: "Résoudre l’équation différentielle et utiliser T(0)=18.", notion: "Équation y′=ay+b", recognition: "la solution d’équilibre vaut −b/a=26", reasoning: "Les solutions sont y(t)=26+Ce^(−0,035t). La condition initiale donne 18=26+C, donc C=−8.", calculations: ["T(t)=26−8e^(−0,035t)"], redaction: "La fonction obtenue est définie sur [0;+∞[ et vérifie à la fois l’équation et la condition initiale.", result: "T(t)=26−8e^(−0,035t).", commonError: "Oublier la constante particulière 26.", },
      { id: "j1-ex3-a3", label: "Partie A · question 3", question: "Quand la température atteint-elle 20 °C ?", notion: "Équation exponentielle", recognition: "le temps t est exprimé en dizaines de minutes", reasoning: "On isole l’exponentielle, puis on applique le logarithme.", calculations: ["26−8e^(−0,035t)=20 ⇔ e^(−0,035t)=3/4", "t=−ln(3/4)/0,035≈8,219", "8,219 dizaines de minutes≈82,19 min"], redaction: "La conversion finale donne environ 1 heure et 22 minutes après le déclenchement.", result: "La pièce atteint 20 °C après environ 1 h 22 min.", commonError: "Lire 8,219 comme des minutes au lieu de dizaines de minutes.", },
      { id: "j1-ex3-a4", label: "Partie A · question 4", question: "Une panne peut-elle conduire au-delà de 28 °C dans ce modèle ?", notion: "Limite d’une exponentielle", recognition: "e^(−0,035t) reste positif et tend vers 0", reasoning: "Pour tout t≥0, T(t)=26−8e^(−0,035t)<26. La limite vaut 26.", redaction: "La température modélisée reste strictement inférieure à 26 °C, même si le chauffage ne s’éteint pas.", result: "Non, elle ne peut pas dépasser 28 °C selon ce modèle.", commonError: "Se contenter de la limite sans remarquer que la fonction reste sous 26.", },
      { id: "j1-ex3-b12", label: "Partie B · questions 1 et 2", question: "Calculer u₁ puis établir uₙ>10 par récurrence.", notion: "Suite récurrente et récurrence", recognition: "le terme exponentiel est toujours strictement positif", reasoning: "L’initialisation est u₀=20>10. Si uₙ>10, alors 0,965uₙ+0,35>10 et l’ajout positif conserve l’inégalité stricte.", calculations: ["u₁=0,965×20+0,35+0,07=19,72", "uₙ₊₁>0,965×10+0,35=10"], redaction: "L’initialisation et l’hérédité étant établies, uₙ>10 pour tout entier naturel n.", result: "u₁=19,72 et la suite est minorée strictement par 10.", commonError: "Remplacer e^(−0,1n) par 0 dans l’hérédité au lieu d’utiliser sa positivité.", },
      { id: "j1-ex3-b34", label: "Partie B · questions 3 et 4", question: "Prouver la convergence et déterminer la limite.", notion: "Théorème de convergence monotone", recognition: "la décroissance est admise et la minoration vient d’être démontrée", reasoning: "Une suite décroissante et minorée converge. En passant à la limite, e^(−0,1n) tend vers 0.", calculations: ["ℓ=0,965ℓ+0,35", "0,035ℓ=0,35 donc ℓ=10"], redaction: "Si le refroidissement se poursuivait sans redémarrage, la température se rapprocherait de 10 °C.", result: "La suite converge vers 10.", commonError: "Conclure que la pièce atteint nécessairement 10 °C : une limite n’est pas forcément atteinte.", },
      { id: "j1-ex3-b5", label: "Partie B · question 5", question: "Compléter l’algorithme de seuil et déterminer le redémarrage.", notion: "Boucle while et indice de suite", recognition: "on poursuit tant que u est strictement supérieur à 18", reasoning: "La mise à jour doit employer l’indice n courant, puis n est incrémenté. Le premier terme inférieur ou égal à 18 est u₈.", calculations: ["while u > 18:", "u = 0.965*u + 0.35 + 0.07*exp(-0.1*n)", "n = n + 1", "u₇≈18,122 ; u₈≈17,872"], redaction: "La boucle s’arrête à n=8, lorsque la condition u>18 devient fausse.", result: "Le chauffage redémarre à partir de 8 dizaines de minutes, soit 80 minutes.", commonError: "Incrémenter n avant le calcul de u et décaler ainsi le terme exponentiel.", },
    ],
  },
  {
    id: "j1-ex4", title: "Exercice 4 — fonction logarithme et aire", points: "5 points officiels", topics: "Lecture graphique, dérivation, convexité, variations, équation et intégrale.", difficulty: "Soutenue", skill: "Relier un graphique aux paramètres d’une fonction puis mener une étude complète.",
    items: [
      { id: "j1-ex4-a1", label: "Partie A · question 1", question: "Identifier le paramètre a.", notion: "Image d’un point", recognition: "A(0;1) appartient à la courbe", reasoning: "Comme ln(1)=0, f(0)=a.", calculations: ["f(0)=a+b ln(1)=a=1"], redaction: "L’ordonnée du point A est 1, donc f(0)=1 et a=1.", result: "a=1.", commonError: "Chercher la pente alors que seule l’ordonnée du point est utile.", },
      { id: "j1-ex4-a23", label: "Partie A · questions 2 et 3", question: "Lire f′(0), le signe de f″(1), dériver et identifier b.", notion: "Tangente, concavité et dérivation", recognition: "la pente de la tangente donne f′(0), tandis qu’une courbe concave donne f″<0", reasoning: "Le graphique donne une pente 4 en A et une concavité vers le bas en x=1. La dérivée du quotient logarithmique vaut (1−ln(x+1))/(x+1)².", calculations: ["f′(x)=b(1−ln(x+1))/(x+1)²", "f′(0)=b=4", "f″(1)=4(2ln 2−3)/8<0"], redaction: "La valeur lue f′(0)=4 concorde avec la concavité observée en x=1.", result: "f′(0)=4, f″(1)<0 et b=4.", commonError: "Confondre la valeur f(0)=1 avec la pente f′(0)=4.", },
      { id: "j1-ex4-b123", label: "Partie B · questions 1 à 3", question: "Trouver l’asymptote et dresser les variations complètes.", notion: "Limite et signe de dérivée", recognition: "ln(x+1)/(x+1) tend vers 0 et f′ a le signe de 1−ln(x+1)", reasoning: "L’inéquation 1−ln(x+1)>0 équivaut à x<e−1 sur le domaine x>−1.", calculations: ["lim(x→+∞) f(x)=1", "f croît sur ]−1;e−1] puis décroît sur [e−1;+∞[", "f(e−1)=1+4/e"], redaction: "Avec la limite admise −∞ en −1, le maximum exact est atteint en x=e−1. À l’infini, la courbe se rapproche de y=1.", result: "Asymptote y=1 ; maximum 1+4/e.", commonError: "Oublier le domaine x>−1 en résolvant l’inéquation logarithmique.", },
      { id: "j1-ex4-b4", label: "Partie B · question 4", question: "Montrer l’unicité de la solution de f(x)=1,5 sur [2;+∞[.", notion: "Valeurs intermédiaires et monotonie", recognition: "f est continue et strictement décroissante sur cet intervalle", reasoning: "On a f(2)>1,5 et la limite de f vaut 1<1,5. La continuité assure l’existence et la stricte décroissance l’unicité.", calculations: ["f(2)=1+4ln(3)/3≈2,465", "8ln(x+1)=x+1", "solution α≈25,093"], redaction: "Le théorème des valeurs intermédiaires, complété par la monotonie, donne une unique solution.", result: "α≈25,1 au dixième.", commonError: "Donner une valeur de calculatrice sans démontrer l’unicité.", },
      { id: "j1-ex4-b5", label: "Partie B · question 5", question: "Calculer l’intégrale puis l’aire sous la courbe entre 0 et 2.", notion: "Primitive de u′/u et aire", recognition: "la dérivée de ln(x+1) est 1/(x+1)", reasoning: "Une primitive de ln(x+1)/(x+1) est 1/2[ln(x+1)]². La fonction est positive sur [0;2], donc l’intégrale de f est bien l’aire.", calculations: ["∫₀² ln(x+1)/(x+1) dx=1/2(ln 3)²", "∫₀² f(x)dx=2+4×1/2(ln 3)²"], redaction: "Les bornes verticales et l’axe des abscisses délimitent le domaine demandé ; aucune valeur absolue supplémentaire n’est nécessaire car f>0.", result: "Aire=2+2(ln 3)² unités d’aire.", commonError: "Oublier l’intégrale du terme constant 1, qui vaut 2 sur [0;2].", },
    ],
  },
] as const;

export const terminaleJ2Exercises: readonly ExamCorrectionExercise[] = [
  {
    id: "j2-ex1", title: "Exercice 1 — tétraèdre ABCD", points: "5 points officiels", topics: "Plans, droite orthogonale, projection, aire, volume et coplanarité.", difficulty: "Intermédiaire", skill: "Enchaîner produit scalaire, représentation paramétrique et formules géométriques.",
    items: [
      { id: "j2-ex1-14", label: "Questions 1 à 4", question: "Déterminer le plan (ABC) et le projeté H de D.", notion: "Plan et projection orthogonale", recognition: "deux vecteurs non colinéaires définissent le plan et un vecteur normal dirige la perpendiculaire", reasoning: "AB=(1;−3;−1) et AC=(−2;−2;0) ne sont pas colinéaires. Le vecteur n=(1;−1;4) leur est orthogonal. La droite D+t n coupe le plan pour t=−1/6.", calculations: ["(ABC): x−y+4z−5=0", "D+t n=(t;−t;2+4t)", "18t+3=0 donc t=−1/6", "H=(−1/6;1/6;4/3)"], redaction: "Le point H appartient au plan et DH est parallèle au vecteur normal ; c’est donc le projeté orthogonal.", result: "H(−1/6;1/6;4/3).", commonError: "Changer arbitrairement les signes du vecteur directeur dans une seule coordonnée.", },
      { id: "j2-ex1-5", label: "Question 5", question: "Montrer que ABC est isocèle en B et calculer son aire.", notion: "Normes, produit scalaire et aire d’un triangle", recognition: "isocèle en B signifie BA=BC, puis l’aire s’obtient avec (1/2)×BA×BC×sin(B)", reasoning: "BA=(−1;3;1) et BC=(−3;1;1) ont toutes deux une norme √11. Leur produit scalaire vaut 7, donc cos(B)=7/11 et sin(B)=6√2/11.", calculations: ["‖BA‖²=11=‖BC‖² ; BA·BC=7", "sin(B)=√(1−(7/11)²)=6√2/11", "Aire(ABC)=(1/2)×√11×√11×6√2/11=3√2"], redaction: "L’égalité des deux longueurs établit la nature du triangle ; le produit scalaire donne ensuite le sinus de l’angle en B et l’aire exacte.", result: "ABC est isocèle en B et son aire vaut 3√2.", commonError: "Utiliser le cosinus à la place du sinus dans la formule de l’aire.", },
      { id: "j2-ex1-6", label: "Question 6", question: "Calculer le volume puis l’aire de BCD.", notion: "Volume d’un tétraèdre", recognition: "on peut choisir successivement deux bases différentes pour le même volume", reasoning: "La hauteur issue de D vers (ABC) est DH=1/√2. Puis on utilise la distance admise de A au plan (BCD), égale à √2.", calculations: ["V=(1/3)×3√2×1/√2=1", "1=(1/3)×Aire(BCD)×√2", "Aire(BCD)=3/√2=3√2/2"], redaction: "Le volume ne dépend pas du choix de la face utilisée comme base.", result: "V(ABCD)=1 et Aire(BCD)=3√2/2.", commonError: "Utiliser directement la distance DH comme hauteur relative à la base BCD.", },
      { id: "j2-ex1-7", label: "Question 7", question: "Étudier le point Dₖ et la possibilité que A soit son projeté.", notion: "Coplanarité et direction normale", recognition: "Dₖ est coplanaire s’il vérifie l’équation du plan", reasoning: "L’équation donne 4k−5=0. Si A était le projeté d’un autre Dₖ, le vecteur ADₖ devrait être colinéaire à n ; ses deux premières coordonnées rendent cela impossible.", calculations: ["k=5/4 ; Dₖ=(0;0;5/4)", "ADₖ=(−2;−1;k−1)", "−2=λ et −1=−λ imposeraient λ=−2 et λ=1"], redaction: "Pour k=5/4, Dₖ appartient déjà au plan : son projeté est lui-même. Aucun k ne donne A comme projeté.", result: "k=5/4 pour la coplanarité ; aucune valeur pour la seconde demande.", commonError: "Croire que tout point de l’axe des cotes se projette sur un sommet du plan.", },
    ],
  },
  {
    id: "j2-ex2", title: "Exercice 2 — pollution d’un bassin", points: "5 points officiels", topics: "Suite récurrente, algorithme, équation différentielle, limite et seuil.", difficulty: "Accessible", skill: "Comparer un modèle discret et un modèle continu sans confondre leurs variables.",
    items: [
      { id: "j2-ex2-a12", label: "Partie A · questions 1 et 2", question: "Calculer V₁, V₂ et compléter la fonction Python.", notion: "Récurrence affine", recognition: "chaque heure applique exactement la même mise à jour", reasoning: "On part de V₀=0 et on répète n fois la formule.", calculations: ["V₁=0,995×0+6=6", "V₂=0,995×6+6=11,97", "v=0 puis, dans la boucle, v=0.995*v+6"], redaction: "La boucle range(n) effectue n mises à jour et renvoie donc Vₙ.", result: "V₁=6 L et V₂=11,97 L.", commonError: "Initialiser v à 6, ce qui décale tous les indices d’une heure.", },
      { id: "j2-ex2-a34", label: "Partie A · questions 3 et 4", question: "Montrer la croissance, la borne 1 200 et calculer la limite.", notion: "Récurrence et convergence monotone", recognition: "l’écart entre deux termes est multiplié par 0,995", reasoning: "L’initialisation donne 0≤6≤1 200. Si Vₙ≤Vₙ₊₁≤1 200, la récurrence conserve l’ordre et la borne. La suite croissante majorée converge.", calculations: ["Vₙ₊₂−Vₙ₊₁=0,995(Vₙ₊₁−Vₙ)≥0", "Vₙ₊₂≤0,995×1 200+6=1 200", "ℓ=0,995ℓ+6 donc ℓ=1 200"], redaction: "Le théorème de convergence monotone s’applique après la double inégalité établie par récurrence.", result: "La suite converge vers 1 200 litres.", commonError: "Passer à la limite avant d’avoir justifié la convergence.", },
      { id: "j2-ex2-b1", label: "Partie B · question 1", question: "Résoudre le modèle continu et étudier v.", notion: "Équation différentielle", recognition: "la valeur d’équilibre est encore 1 200", reasoning: "La solution générale est 1 200+Ce^(−0,005t). La condition v(0)=0 donne C=−1 200.", calculations: ["v(t)=1 200(1−e^(−0,005t))", "v′(t)=6e^(−0,005t)>0", "lim v(t)=1 200"], redaction: "La fonction est strictement croissante sur [0;+∞[ et se rapproche de 1 200.", result: "v(t)=1 200(1−e^(−0,005t)), croissante, de limite 1 200.", commonError: "Écrire une exponentielle croissante e^(0,005t), incompatible avec une limite finie.", },
      { id: "j2-ex2-b23", label: "Partie B · questions 2 et 3", question: "Décider du nettoyage à 5 % et calculer le seuil de 50 L.", notion: "Comparaison à une limite et équation exponentielle", recognition: "5 % de 30 000 L vaut 1 500 L", reasoning: "Le modèle reste sous 1 200 L, donc sous 1 500 L. Pour 50 L, la croissance permet de résoudre l’égalité puis d’indiquer l’instant au-delà duquel le seuil est dépassé.", calculations: ["0,05×30 000=1 500", "1 200(1−e^(−0,005t))=50", "t=200 ln(24/23)≈8,512 h≈8 h 31 min"], redaction: "Le nettoyage complet n’est pas déclenché dans ce modèle, mais le seuil préventif de 50 L est dépassé après l’instant calculé.", result: "Pas de nettoyage au seuil de 5 % ; dépassement de 50 L après 200 ln(24/23) h, soit environ 8 h 31 min.", commonError: "Comparer 1 200 à 5 % sans convertir les 5 % en litres.", },
    ],
  },
  {
    id: "j2-ex3", title: "Exercice 3 — quatre affirmations", points: "4 points officiels", topics: "Probabilités conditionnelles, loi binomiale, Bienaymé-Tchebychev et dénombrement.", difficulty: "Soutenue", skill: "Choisir la formule adaptée et distinguer valeur exacte, approximation et borne.",
    items: [
      { id: "j2-ex3-1", label: "Affirmation 1", question: "Une femme musicienne professionnelle joue-t-elle de la Pop avec probabilité 0,832 ?", notion: "Probabilité conditionnelle", recognition: "P(F|O)=0,32 est donnée, mais on demande P(O|F)", reasoning: "On calcule d’abord l’intersection puis on divise par P(F).", calculations: ["P(O∩F)=0,52×0,32=0,1664", "P(O|F)=0,1664/0,20=0,832"], redaction: "La valeur annoncée est bien la probabilité conditionnelle recherchée.", result: "Affirmation vraie.", commonError: "Répondre 0,32 en confondant les deux sens de conditionnement.", },
      { id: "j2-ex3-2", label: "Affirmation 2", question: "La probabilité P(X≤340) vaut-elle environ 0,4 ?", notion: "Loi binomiale", recognition: "5 000 essais indépendants de probabilité 0,062 donnent X~B(5000;0,062)", reasoning: "Le calcul de la fonction de répartition donne une probabilité très élevée, cohérente avec une espérance de 310 et un seuil 340 supérieur à la moyenne.", calculations: ["X~B(5 000;0,062)", "P(X≤340)≈0,9617≈1,0 au dixième"], redaction: "L’arrondi au dixième n’est pas 0,4 mais 1,0.", result: "Affirmation fausse.", commonError: "Confondre P(X=340) et P(X≤340), ou lire une mauvaise commande de calculatrice.", },
      { id: "j2-ex3-3", label: "Affirmation 3", question: "Bienaymé-Tchebychev garantit-elle plus de 95 % entre 230 et 390 ?", notion: "Inégalité de Bienaymé-Tchebychev", recognition: "l’intervalle est centré sur E(X)=310 avec un rayon 80", reasoning: "On calcule la variance binomiale puis on minore la probabilité complémentaire.", calculations: ["E(X)=310 ; V(X)=5 000×0,062×0,938=290,78", "P(|X−310|<80)≥1−290,78/80²≈0,9546"], redaction: "La borne obtenue est strictement supérieure à 0,95 ; l’inégalité suffit donc à l’affirmer.", result: "Affirmation vraie.", commonError: "Utiliser l’écart-type au numérateur à la place de la variance.", },
      { id: "j2-ex3-4", label: "Affirmation 4", question: "Peut-on former 120 équipes respectant la composition imposée ?", notion: "Combinaisons", recognition: "on choisit 2 musiciens parmi 4 et 3 non-musiciens parmi 6", reasoning: "L’ordre à l’intérieur d’une équipe n’intervient pas.", calculations: ["C(4,2)×C(6,3)=6×20=120"], redaction: "Chaque choix détermine une équipe de cinq personnes ayant la composition demandée.", result: "Affirmation vraie.", commonError: "Diviser par 2 alors que l’on compte ici les compositions possibles d’une équipe, pas les matchs non ordonnés.", },
    ],
  },
  {
    id: "j2-ex4", title: "Exercice 4 — logo industriel", points: "6 points officiels", topics: "Lecture graphique, primitives, exponentielle, variations, intégration par parties et volume.", difficulty: "Soutenue", skill: "Combiner étude de fonction et interprétation géométrique d’un modèle.",
    items: [
      { id: "j2-ex4-a", label: "Partie A · questions 1 à 3", question: "Lire f′(1), la racine, f′(1/2) et identifier deux primitives.", notion: "Tangentes et primitives", recognition: "la dérivée s’annule à une tangente horizontale et une primitive varie selon le signe de f", reasoning: "La courbe coupe l’axe en x=1/2 et la tangente en ce point passe par B(1;e²). Sa pente vaut 2e². Une primitive doit décroître avant 1/2 puis croître après.", calculations: ["f′(1)=0", "f(x)=0 ⇔ x=1/2 sur [0;3]", "f′(1/2)=(e²−0)/(1−1/2)=2e²"], redaction: "Les courbes C₁ et C₂ ont toutes deux leur minimum en x=1/2 et ne diffèrent que d’une constante : ce sont les deux primitives.", result: "f′(1)=0 ; racine 1/2 ; f′(1/2)=2e² ; primitives C₁ et C₂.", commonError: "Choisir une primitive d’après sa ressemblance avec f au lieu d’étudier son sens de variation.", },
      { id: "j2-ex4-b1", label: "Partie B · question 1", question: "Réécrire f et calculer sa limite.", notion: "Croissances comparées", recognition: "une expression polynomiale divisée par une exponentielle tend vers 0", reasoning: "On factorise e² et on pose X=2x−1, qui tend vers +∞.", calculations: ["f(x)=e²(2x−1)/e^(2x−1)", "X/e^X→0"], redaction: "Le facteur constant e² ne change pas la limite.", result: "lim(x→+∞) f(x)=0.", commonError: "Conclure à +∞ parce que le numérateur 2x−1 croît.", },
      { id: "j2-ex4-b2", label: "Partie B · question 2", question: "Dériver et dresser le tableau de variations.", notion: "Dérivée d’un produit", recognition: "l’exponentielle est toujours positive, donc le signe vient de −4x+4", reasoning: "La dérivée est positive avant 1, nulle en 1, négative après.", calculations: ["f′(x)=(−4x+4)e^(−2x+3)", "f(0)=−e³ ; f(1)=e ; lim f=0"], redaction: "La fonction croît de −e³ à e sur [0;1], puis décroît de e vers 0 sur [1;+∞[.", result: "Maximum e atteint en x=1.", commonError: "Attribuer un changement de signe au facteur exponentiel, qui reste strictement positif.", },
      { id: "j2-ex4-b3", label: "Partie B · question 3", question: "Traduire la largeur 0,3 cm et déterminer α.", notion: "Symétrie et théorème des valeurs intermédiaires", recognition: "le contour est symétrique : la hauteur totale vaut 2f(α)", reasoning: "La contrainte 0,3 donne 2f(α)=0,3. Sur [1;+∞[, f décroît continûment de e vers 0, donc l’égalité f(α)=0,15 a une unique solution.", calculations: ["f(α)=0,15", "α≈3,312"], redaction: "L’existence découle des valeurs encadrant 0,15 et l’unicité de la stricte décroissance.", result: "α≈3,3 au dixième.", commonError: "Poser f(α)=0,3 et oublier que le logo comprend la courbe et son symétrique.", },
      { id: "j2-ex4-c", label: "Partie C · questions 1 et 2", question: "Calculer l’intégrale, l’aire du logo et le volume du porte-clé.", notion: "Intégration par parties et volume", recognition: "une primitive simple de (2x−1)e^(−2x+3) est −x e^(−2x+3)", reasoning: "L’intégrale d’une moitié du logo vaut environ 3,6. La symétrie double l’aire, puis l’épaisseur 0,2 cm convertit l’aire en volume.", calculations: ["I=[−x e^(−2x+3)]₀,₅^3,3≈3,604≈3,6", "Aire≈2I≈7,2 cm²", "Volume≈7,2×0,2=1,44 cm³"], redaction: "En conservant la précision pendant le calcul puis en arrondissant à la fin, le volume demandé vaut 1,4 cm³ au dixième.", result: "I≈3,6 et volume≈1,4 cm³.", commonError: "Oublier le facteur 2 dû à la symétrie ou arrondir I trop tôt dans un calcul plus précis.", },
    ],
  },
] as const;
