export type QuizQuestion = {
  id: string;
  themeId: string;
  themeLabel: string;
  prompt: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  resourceHref: string;
  resourceLabel: string;
};

export const quizQuestions: QuizQuestion[] = [
  {
    id: "q1",
    themeId: "suites",
    themeLabel: "Suites",
    prompt: "On définit u₀ = 3 et uₙ₊₁ = 2uₙ − 1. Quelle est la valeur de u₂ ?",
    options: ["5", "7", "9", "11"],
    correctIndex: 2,
    explanation: "u₁ = 2 × 3 − 1 = 5, puis u₂ = 2 × 5 − 1 = 9.",
    resourceHref: "/methodes-maths-terminale/etudier-une-suite",
    resourceLabel: "Revoir la méthode sur les suites",
  },
  {
    id: "q2",
    themeId: "suites",
    themeLabel: "Suites",
    prompt: "Une suite géométrique de premier terme positif a pour raison 0,8. Quelle est sa limite ?",
    options: ["0", "0,8", "+∞", "Elle n’a jamais de limite"],
    correctIndex: 0,
    explanation: "Comme |0,8| < 1, les puissances 0,8ⁿ tendent vers 0 ; la suite géométrique tend donc vers 0.",
    resourceHref: "/programme-maths-terminale/suites",
    resourceLabel: "Revoir le cours sur les suites",
  },
  {
    id: "q3",
    themeId: "limites",
    themeLabel: "Limites",
    prompt: "Quelle est la limite de (3x² − 1)/(x² + 2) lorsque x tend vers +∞ ?",
    options: ["0", "1", "3", "+∞"],
    correctIndex: 2,
    explanation: "Le numérateur et le dénominateur ont le même degré. La limite est le quotient des coefficients dominants : 3/1 = 3.",
    resourceHref: "/methodes-maths-terminale/calculer-une-limite",
    resourceLabel: "Revoir la méthode sur les limites",
  },
  {
    id: "q4",
    themeId: "limites",
    themeLabel: "Limites",
    prompt: "Quelle est la limite de xe⁻ˣ lorsque x tend vers +∞ ?",
    options: ["−∞", "0", "1", "+∞"],
    correctIndex: 1,
    explanation: "xe⁻ˣ = x/eˣ. Par croissance comparée, l’exponentielle domine x en +∞, donc le quotient tend vers 0.",
    resourceHref: "/programme-maths-terminale/limites",
    resourceLabel: "Revoir les limites de référence",
  },
  {
    id: "q5",
    themeId: "derivation-convexite",
    themeLabel: "Dérivation et convexité",
    prompt: "Si f(x) = (x² + 1)eˣ, quelle est l’expression de f’(x) ?",
    options: ["2xeˣ", "(x² + 2x + 1)eˣ", "(x² + 1)eˣ", "(2x + 1)eˣ"],
    correctIndex: 1,
    explanation: "Par la formule du produit, f’(x) = 2xeˣ + (x² + 1)eˣ = (x² + 2x + 1)eˣ.",
    resourceHref: "/programme-maths-terminale/derivation-convexite",
    resourceLabel: "Revoir dérivation et convexité",
  },
  {
    id: "q6",
    themeId: "derivation-convexite",
    themeLabel: "Dérivation et convexité",
    prompt: "Si f est deux fois dérivable sur un intervalle I et f’’(x) ≥ 0 sur I, que peut-on affirmer ?",
    options: ["f est croissante", "f est décroissante", "f est convexe", "f est constante"],
    correctIndex: 2,
    explanation: "Le signe positif ou nul de f’’ sur l’intervalle caractérise la convexité de f sur cet intervalle.",
    resourceHref: "/methodes-maths-terminale/tableau-variation",
    resourceLabel: "Revoir variations et convexité",
  },
  {
    id: "q7",
    themeId: "logarithme-exponentielle",
    themeLabel: "Logarithme et exponentielle",
    prompt: "Que vaut ln(e³) ?",
    options: ["e³", "3", "3e", "1"],
    correctIndex: 1,
    explanation: "Le logarithme népérien et l’exponentielle sont réciproques : ln(eˣ) = x pour tout réel x.",
    resourceHref: "/methodes-maths-terminale/logarithme",
    resourceLabel: "Revoir la méthode logarithme",
  },
  {
    id: "q8",
    themeId: "logarithme-exponentielle",
    themeLabel: "Logarithme et exponentielle",
    prompt: "Quelle est la solution réelle de e²ˣ = 5 ?",
    options: ["x = 5/2", "x = e⁵/²", "x = ln(5)/2", "x = 2ln(5)"],
    correctIndex: 2,
    explanation: "On applique ln aux deux membres : 2x = ln(5), donc x = ln(5)/2.",
    resourceHref: "/articles/exponentielle-terminale-methodes",
    resourceLabel: "Revoir les méthodes sur l’exponentielle",
  },
  {
    id: "q9",
    themeId: "probabilites",
    themeLabel: "Probabilités",
    prompt: "On sait que P(A) = 0,4 et P(B | A) = 0,3. Que vaut P(A ∩ B) ?",
    options: ["0,1", "0,12", "0,7", "1,2"],
    correctIndex: 1,
    explanation: "P(A ∩ B) = P(A) × P(B | A) = 0,4 × 0,3 = 0,12.",
    resourceHref: "/methodes-maths-terminale/probabilites-conditionnelles",
    resourceLabel: "Revoir les probabilités conditionnelles",
  },
  {
    id: "q10",
    themeId: "probabilites",
    themeLabel: "Probabilités",
    prompt: "A et B sont indépendants, avec P(A) = 0,5 et P(B) = 0,2. Que vaut P(A ∩ B) ?",
    options: ["0", "0,1", "0,3", "0,7"],
    correctIndex: 1,
    explanation: "L’indépendance donne P(A ∩ B) = P(A)P(B) = 0,5 × 0,2 = 0,1.",
    resourceHref: "/demonstrations-bac-maths-terminale#independance",
    resourceLabel: "Revoir l’indépendance",
  },
  {
    id: "q11",
    themeId: "probabilites",
    themeLabel: "Probabilités",
    prompt: "Si X suit une loi binomiale B(10 ; 0,3), quelle est son espérance ?",
    options: ["0,3", "3", "7", "10"],
    correctIndex: 1,
    explanation: "Pour X suivant B(n ; p), E(X) = np. Ici E(X) = 10 × 0,3 = 3.",
    resourceHref: "/articles/probabilites-loi-binomiale-terminale",
    resourceLabel: "Revoir la loi binomiale",
  },
  {
    id: "q12",
    themeId: "integrales",
    themeLabel: "Intégrales",
    prompt: "Que vaut l’intégrale de 0 à 1 de 2x dx ?",
    options: ["0", "1", "2", "4"],
    correctIndex: 1,
    explanation: "Une primitive de 2x est x². Ainsi [x²]₀¹ = 1² − 0² = 1.",
    resourceHref: "/methodes-maths-terminale/integrales",
    resourceLabel: "Revoir la méthode sur les intégrales",
  },
  {
    id: "q13",
    themeId: "integrales",
    themeLabel: "Intégrales",
    prompt: "Quelle est la forme générale des primitives de f(x) = 3x² − 2 sur ℝ ?",
    options: ["x³ − 2x + C", "6x − 2 + C", "x³ − 2 + C", "3x³ − 2x + C"],
    correctIndex: 0,
    explanation: "La dérivée de x³ − 2x + C est 3x² − 2. La constante réelle C décrit toutes les primitives sur ℝ.",
    resourceHref: "/demonstrations-bac-maths-terminale#primitives",
    resourceLabel: "Revoir les primitives",
  },
  {
    id: "q14",
    themeId: "geometrie-espace",
    themeLabel: "Géométrie dans l’espace",
    prompt: "Dans un repère orthonormé, quel vecteur est normal au plan 2x − y + 3z − 4 = 0 ?",
    options: ["(2 ; −1 ; 3)", "(2 ; 1 ; 3)", "(−4 ; 0 ; 0)", "(1 ; 1 ; 1)"],
    correctIndex: 0,
    explanation: "Les coefficients de x, y et z donnent un vecteur normal au plan : n⃗ = (2 ; −1 ; 3).",
    resourceHref: "/methodes-maths-terminale/geometrie-espace",
    resourceLabel: "Revoir la géométrie dans l’espace",
  },
  {
    id: "q15",
    themeId: "geometrie-espace",
    themeLabel: "Géométrie dans l’espace",
    prompt: "Dans un repère orthonormé, les vecteurs u⃗ = (1 ; 2 ; −1) et v⃗ = (2 ; −1 ; 0) sont-ils orthogonaux ?",
    options: ["Oui, car leur produit scalaire vaut 0", "Oui, car ils sont colinéaires", "Non, car leur produit scalaire vaut 1", "On ne peut pas savoir"],
    correctIndex: 0,
    explanation: "u⃗ · v⃗ = 1 × 2 + 2 × (−1) + (−1) × 0 = 0. Les vecteurs sont donc orthogonaux.",
    resourceHref: "/programme-maths-terminale/geometrie-espace",
    resourceLabel: "Revoir vecteurs, droites et plans",
  },
  {
    id: "q16",
    themeId: "equations-differentielles",
    themeLabel: "Équations différentielles",
    prompt: "Quelles sont les solutions de y’ = 3y sur ℝ ?",
    options: ["y(x) = 3x + C", "y(x) = Ce³ˣ", "y(x) = eˣ + 3", "y(x) = Cx³"],
    correctIndex: 1,
    explanation: "Les solutions de y’ = ay sont y(x) = Ce^(ax). Avec a = 3, on obtient y(x) = Ce³ˣ.",
    resourceHref: "/equations-differentielles-terminale#cas",
    resourceLabel: "Revoir les deux formes de référence",
  },
  {
    id: "q17",
    themeId: "derivation-convexite",
    themeLabel: "Dérivation et convexité",
    prompt: "Une fonction f est deux fois dérivable et f’’ change de signe en a. Quelle conclusion est justifiée ?",
    options: ["La courbe admet un point d’inflexion d’abscisse a", "f admet un maximum en a", "f(a) = 0", "f’ change nécessairement de signe en a"],
    correctIndex: 0,
    explanation: "Le changement de signe de f’’ en a traduit un changement de convexité : la courbe admet un point d’inflexion d’abscisse a.",
    resourceHref: "/demonstrations-bac-maths-terminale#convexite",
    resourceLabel: "Revoir la démonstration liée à la convexité",
  },
  {
    id: "q18",
    themeId: "algorithmique-python",
    themeLabel: "Algorithmique Python",
    prompt: "Quelles valeurs prend k dans l’instruction for k in range(4) ?",
    options: ["1, 2, 3, 4", "0, 1, 2, 3", "0, 1, 2, 3, 4", "4 uniquement"],
    correctIndex: 1,
    explanation: "range(4) commence à 0 et exclut la borne 4 : k prend successivement les valeurs 0, 1, 2 et 3.",
    resourceHref: "/python-bac-maths-terminale#suite-recurrence",
    resourceLabel: "Revoir les boucles for",
  },
  {
    id: "q19",
    themeId: "algorithmique-python",
    themeLabel: "Algorithmique Python",
    prompt: "Que produit le programme : s = 0 puis, pour k dans range(1, 4), s = s + k ?",
    options: ["3", "6", "10", "Une erreur"],
    correctIndex: 1,
    explanation: "range(1, 4) fournit 1, 2 et 3. La variable s accumule donc 1 + 2 + 3 = 6.",
    resourceHref: "/python-bac-maths-terminale#somme",
    resourceLabel: "Revoir le calcul d’une somme",
  },
  {
    id: "q20",
    themeId: "logarithme-exponentielle",
    themeLabel: "Logarithme et exponentielle",
    prompt: "Quelle est la solution de ln(x) = 2 sur ]0 ; +∞[ ?",
    options: ["x = e²", "x = 2", "x = e/2", "x = ln(2)"],
    correctIndex: 0,
    explanation: "L’exponentielle et le logarithme sont réciproques : ln(x) = 2 équivaut à x = e² sur le domaine x > 0.",
    resourceHref: "/formules-bac-maths-terminale#exponentielle-logarithme",
    resourceLabel: "Revoir les formules exponentielle et logarithme",
  },
];

export const quizThemes = Array.from(
  new Map(
    quizQuestions.map((question) => [
      question.themeId,
      { id: question.themeId, label: question.themeLabel },
    ]),
  ).values(),
);
