export const chapterNames = [
  "Suites",
  "Limites",
  "Continuité",
  "Dérivation et variations",
  "Convexité",
  "Exponentielle et logarithme",
  "Primitives et intégrales",
  "Équations différentielles",
  "Probabilités conditionnelles",
  "Loi binomiale",
  "Dénombrement",
  "Géométrie dans l’espace",
  "Python et algorithmique",
] as const;

export type ChapterName = (typeof chapterNames)[number];
export type AnnaleDifficulty = "Accessible" | "Intermédiaire" | "Soutenue";

export type ChapterAnnaleExercise = {
  id: string;
  year: "2024" | "2025" | "2026";
  center: string;
  day: "Jour 1" | "Jour 2";
  exercise: string;
  title: string;
  mainChapter: ChapterName;
  secondaryChapters: readonly ChapterName[];
  exactNotions: string;
  difficulty: AnnaleDifficulty;
  pdfUrl: string;
  correctionHref: string;
  methodHref: string;
};

const pdf = {
  y2024j1: "https://eduscol.education.gouv.fr/sites/default/files/document/24-matj1me1v1-0pdf-106221.pdf",
  y2024j2: "https://eduscol.education.gouv.fr/sites/default/files/document/24-matj2me2v1pdf-106281.pdf",
  y2025j1: "https://www.education.gouv.fr/sites/default/files/2025-06/baccalaur-at-g-n-ral-2025-math-matiques-440856.pdf",
  y2025j2: "https://www.education.gouv.fr/sites/default/files/2025-06/baccalaur-at-g-n-ral-2025-math-matiques-440988.pdf",
  y2026j1: "https://www.education.gouv.fr/sites/default/files/document/baccalaureat-general-2026-mathematiques-517598.pdf",
  y2026j2: "https://www.education.gouv.fr/sites/default/files/document/baccalaureat-general-2026-mathematiques-jour-2-517817.pdf",
} as const;

export const chapterExercises: readonly ChapterAnnaleExercise[] = [
  { id: "2024-j1-e1", year: "2024", center: "Métropole, La Réunion et Mayotte", day: "Jour 1", exercise: "Exercice 1", title: "Vrai/faux fonctions et suites", mainChapter: "Suites", secondaryChapters: ["Limites", "Exponentielle et logarithme", "Équations différentielles"], exactNotions: "Limite de xe⁻ˣ, vérification d’une EDO, encadrement et contre-exemple de convergence.", difficulty: "Intermédiaire", pdfUrl: pdf.y2024j1, correctionHref: "/sujet-bac-maths-2024-corrige#jour-1", methodHref: "/methodes-maths-terminale/etudier-une-suite" },
  { id: "2024-j1-e2", year: "2024", center: "Métropole, La Réunion et Mayotte", day: "Jour 1", exercise: "Exercice 2", title: "Satisfaction et livraison", mainChapter: "Probabilités conditionnelles", secondaryChapters: ["Loi binomiale"], exactNotions: "Arbre, Bayes, binomiale, somme de variables indépendantes et Tchebychev.", difficulty: "Intermédiaire", pdfUrl: pdf.y2024j1, correctionHref: "/sujet-bac-maths-2024-corrige#jour-1", methodHref: "/methodes-maths-terminale/probabilites-conditionnelles" },
  { id: "2024-j1-e3", year: "2024", center: "Métropole, La Réunion et Mayotte", day: "Jour 1", exercise: "Exercice 3", title: "Tétraèdre et distance", mainChapter: "Géométrie dans l’espace", secondaryChapters: [], exactNotions: "Plan, projection orthogonale, aire, volume et distance point-plan.", difficulty: "Intermédiaire", pdfUrl: pdf.y2024j1, correctionHref: "/sujet-bac-maths-2024-corrige#jour-1", methodHref: "/methodes-maths-terminale/geometrie-espace" },
  { id: "2024-j1-e4", year: "2024", center: "Métropole, La Réunion et Mayotte", day: "Jour 1", exercise: "Exercice 4", title: "Logarithme, fonction auxiliaire et aire", mainChapter: "Exponentielle et logarithme", secondaryChapters: ["Limites", "Continuité", "Dérivation et variations", "Convexité", "Primitives et intégrales"], exactNotions: "Racine unique, composition f(1/x), variations, position relative et intégration par parties.", difficulty: "Soutenue", pdfUrl: pdf.y2024j1, correctionHref: "/sujet-bac-maths-2024-corrige#jour-1", methodHref: "/methodes-maths-terminale/logarithme" },
  { id: "2024-j2-e1", year: "2024", center: "Métropole, La Réunion et Mayotte", day: "Jour 2", exercise: "Exercice 1", title: "Réussite à un examen", mainChapter: "Probabilités conditionnelles", secondaryChapters: ["Loi binomiale"], exactNotions: "Probabilités totales, Bayes, binomiale, moyenne, variance et Tchebychev.", difficulty: "Intermédiaire", pdfUrl: pdf.y2024j2, correctionHref: "/sujet-bac-maths-2024-corrige#jour-2", methodHref: "/methodes-maths-terminale/probabilites-conditionnelles" },
  { id: "2024-j2-e2", year: "2024", center: "Métropole, La Réunion et Mayotte", day: "Jour 2", exercise: "Exercice 2", title: "Chlore d’une piscine", mainChapter: "Suites", secondaryChapters: ["Limites", "Équations différentielles", "Python et algorithmique"], exactNotions: "Récurrence affine, convergence, seuil Python et équation y′=ay+b.", difficulty: "Intermédiaire", pdfUrl: pdf.y2024j2, correctionHref: "/sujet-bac-maths-2024-corrige#jour-2", methodHref: "/methodes-maths-terminale/etudier-une-suite" },
  { id: "2024-j2-e3", year: "2024", center: "Métropole, La Réunion et Mayotte", day: "Jour 2", exercise: "Exercice 3", title: "Fonction et distance minimale", mainChapter: "Dérivation et variations", secondaryChapters: ["Limites", "Continuité", "Convexité", "Exponentielle et logarithme"], exactNotions: "Logarithme, racine unique, point d’inflexion, distance au carré et tangente.", difficulty: "Soutenue", pdfUrl: pdf.y2024j2, correctionHref: "/sujet-bac-maths-2024-corrige#jour-2", methodHref: "/methodes-maths-terminale/tableau-variation" },
  { id: "2024-j2-e4", year: "2024", center: "Métropole, La Réunion et Mayotte", day: "Jour 2", exercise: "Exercice 4", title: "Quatre affirmations de géométrie", mainChapter: "Géométrie dans l’espace", secondaryChapters: [], exactNotions: "Plans, coplanarité, intersection de droites et projection orthogonale.", difficulty: "Accessible", pdfUrl: pdf.y2024j2, correctionHref: "/sujet-bac-maths-2024-corrige#jour-2", methodHref: "/methodes-maths-terminale/geometrie-espace" },

  { id: "2025-j1-e1", year: "2025", center: "Métropole, La Réunion et Mayotte", day: "Jour 1", exercise: "Exercice 1", title: "Groupes sanguins", mainChapter: "Probabilités conditionnelles", secondaryChapters: ["Loi binomiale"], exactNotions: "Arbre, loi binomiale, moyenne de variables indépendantes et Tchebychev.", difficulty: "Intermédiaire", pdfUrl: pdf.y2025j1, correctionHref: "/sujet-bac-maths-2025-corrige#jour-1", methodHref: "/methodes-maths-terminale/probabilites-conditionnelles" },
  { id: "2025-j1-e2", year: "2025", center: "Métropole, La Réunion et Mayotte", day: "Jour 1", exercise: "Exercice 2", title: "Fonction logarithmique et aire", mainChapter: "Exponentielle et logarithme", secondaryChapters: ["Limites", "Dérivation et variations", "Convexité", "Primitives et intégrales"], exactNotions: "Lecture graphique, dérivée seconde, tangente, intégration par parties et aire.", difficulty: "Soutenue", pdfUrl: pdf.y2025j1, correctionHref: "/sujet-bac-maths-2025-corrige#jour-1", methodHref: "/methodes-maths-terminale/logarithme" },
  { id: "2025-j1-e3", year: "2025", center: "Métropole, La Réunion et Mayotte", day: "Jour 1", exercise: "Exercice 3", title: "Vrai/faux de géométrie", mainChapter: "Géométrie dans l’espace", secondaryChapters: [], exactNotions: "Droites paramétriques, vecteur normal, coplanarité et distance point-plan.", difficulty: "Intermédiaire", pdfUrl: pdf.y2025j1, correctionHref: "/sujet-bac-maths-2025-corrige#jour-1", methodHref: "/methodes-maths-terminale/geometrie-espace" },
  { id: "2025-j1-e4", year: "2025", center: "Métropole, La Réunion et Mayotte", day: "Jour 1", exercise: "Exercice 4", title: "Évolution de la posidonie", mainChapter: "Suites", secondaryChapters: ["Limites", "Équations différentielles", "Exponentielle et logarithme", "Python et algorithmique"], exactNotions: "Récurrence non linéaire, convergence, seuil et modèle logistique continu.", difficulty: "Soutenue", pdfUrl: pdf.y2025j1, correctionHref: "/sujet-bac-maths-2025-corrige#jour-1", methodHref: "/methodes-maths-terminale/etudier-une-suite" },
  { id: "2025-j2-e1", year: "2025", center: "Métropole, La Réunion et Mayotte", day: "Jour 2", exercise: "Exercice 1", title: "Centre multisports", mainChapter: "Probabilités conditionnelles", secondaryChapters: ["Loi binomiale"], exactNotions: "Arbre, binomiale, somme de variables indépendantes et Tchebychev.", difficulty: "Intermédiaire", pdfUrl: pdf.y2025j2, correctionHref: "/sujet-bac-maths-2025-corrige#jour-2", methodHref: "/methodes-maths-terminale/probabilites-conditionnelles" },
  { id: "2025-j2-e2", year: "2025", center: "Métropole, La Réunion et Mayotte", day: "Jour 2", exercise: "Exercice 2", title: "Droites, plan et projection", mainChapter: "Géométrie dans l’espace", secondaryChapters: [], exactNotions: "Intersection, équation de plan, projection, distance et produit scalaire.", difficulty: "Soutenue", pdfUrl: pdf.y2025j2, correctionHref: "/sujet-bac-maths-2025-corrige#jour-2", methodHref: "/methodes-maths-terminale/geometrie-espace" },
  { id: "2025-j2-e3", year: "2025", center: "Métropole, La Réunion et Mayotte", day: "Jour 2", exercise: "Exercice 3", title: "Quatre affirmations", mainChapter: "Suites", secondaryChapters: ["Limites", "Convexité", "Exponentielle et logarithme"], exactNotions: "Croissance exponentielle, récurrence, convexité graphique et inégalité logarithmique.", difficulty: "Accessible", pdfUrl: pdf.y2025j2, correctionHref: "/sujet-bac-maths-2025-corrige#jour-2", methodHref: "/methodes-maths-terminale/etudier-une-suite" },
  { id: "2025-j2-e4", year: "2025", center: "Métropole, La Réunion et Mayotte", day: "Jour 2", exercise: "Exercice 4", title: "Freinage d’un chariot", mainChapter: "Équations différentielles", secondaryChapters: ["Limites", "Continuité", "Dérivation et variations", "Exponentielle et logarithme", "Primitives et intégrales"], exactNotions: "Vitesse, équation différentielle, seuil unique, intégration par parties et distance.", difficulty: "Soutenue", pdfUrl: pdf.y2025j2, correctionHref: "/sujet-bac-maths-2025-corrige#jour-2", methodHref: "/equations-differentielles-terminale" },

  { id: "2026-j1-e1", year: "2026", center: "Métropole, La Réunion et Mayotte", day: "Jour 1", exercise: "Exercice 1", title: "Traversée en ferry", mainChapter: "Probabilités conditionnelles", secondaryChapters: [], exactNotions: "Arbre, variables aléatoires, espérance, variance, moyenne et Tchebychev.", difficulty: "Intermédiaire", pdfUrl: pdf.y2026j1, correctionHref: "/sujet-bac-maths-2026-corrige#jour-1", methodHref: "/methodes-maths-terminale/probabilites-conditionnelles" },
  { id: "2026-j1-e2", year: "2026", center: "Métropole, La Réunion et Mayotte", day: "Jour 1", exercise: "Exercice 2", title: "Quatre affirmations", mainChapter: "Géométrie dans l’espace", secondaryChapters: ["Dénombrement"], exactNotions: "Plan médiateur, droites, angle par produit scalaire et combinaisons.", difficulty: "Intermédiaire", pdfUrl: pdf.y2026j1, correctionHref: "/sujet-bac-maths-2026-corrige#jour-1", methodHref: "/methodes-maths-terminale/geometrie-espace" },
  { id: "2026-j1-e3", year: "2026", center: "Métropole, La Réunion et Mayotte", day: "Jour 1", exercise: "Exercice 3", title: "Chauffage et refroidissement", mainChapter: "Équations différentielles", secondaryChapters: ["Suites", "Limites", "Exponentielle et logarithme", "Python et algorithmique"], exactNotions: "Équation y′=ay+b, suite récurrente, convergence et boucle de seuil.", difficulty: "Intermédiaire", pdfUrl: pdf.y2026j1, correctionHref: "/sujet-bac-maths-2026-corrige#jour-1", methodHref: "/equations-differentielles-terminale" },
  { id: "2026-j1-e4", year: "2026", center: "Métropole, La Réunion et Mayotte", day: "Jour 1", exercise: "Exercice 4", title: "Fonction logarithme et aire", mainChapter: "Exponentielle et logarithme", secondaryChapters: ["Limites", "Continuité", "Dérivation et variations", "Convexité", "Primitives et intégrales"], exactNotions: "Lecture graphique, asymptote, variations, racine unique, primitive et aire.", difficulty: "Soutenue", pdfUrl: pdf.y2026j1, correctionHref: "/sujet-bac-maths-2026-corrige#jour-1", methodHref: "/methodes-maths-terminale/logarithme" },
  { id: "2026-j2-e1", year: "2026", center: "Métropole, La Réunion et Mayotte", day: "Jour 2", exercise: "Exercice 1", title: "Tétraèdre ABCD", mainChapter: "Géométrie dans l’espace", secondaryChapters: [], exactNotions: "Plan, projection, angle, aire, volume, distance et coplanarité.", difficulty: "Intermédiaire", pdfUrl: pdf.y2026j2, correctionHref: "/sujet-bac-maths-2026-corrige#jour-2", methodHref: "/methodes-maths-terminale/geometrie-espace" },
  { id: "2026-j2-e2", year: "2026", center: "Métropole, La Réunion et Mayotte", day: "Jour 2", exercise: "Exercice 2", title: "Pollution d’un bassin", mainChapter: "Suites", secondaryChapters: ["Limites", "Équations différentielles", "Exponentielle et logarithme", "Python et algorithmique"], exactNotions: "Récurrence affine, convergence, boucle Python, modèle continu et seuil.", difficulty: "Accessible", pdfUrl: pdf.y2026j2, correctionHref: "/sujet-bac-maths-2026-corrige#jour-2", methodHref: "/methodes-maths-terminale/etudier-une-suite" },
  { id: "2026-j2-e3", year: "2026", center: "Métropole, La Réunion et Mayotte", day: "Jour 2", exercise: "Exercice 3", title: "Quatre affirmations", mainChapter: "Probabilités conditionnelles", secondaryChapters: ["Loi binomiale", "Dénombrement"], exactNotions: "Conditionnement, binomiale, Tchebychev et combinaisons.", difficulty: "Soutenue", pdfUrl: pdf.y2026j2, correctionHref: "/sujet-bac-maths-2026-corrige#jour-2", methodHref: "/methodes-maths-terminale/probabilites-conditionnelles" },
  { id: "2026-j2-e4", year: "2026", center: "Métropole, La Réunion et Mayotte", day: "Jour 2", exercise: "Exercice 4", title: "Logo industriel", mainChapter: "Primitives et intégrales", secondaryChapters: ["Limites", "Continuité", "Dérivation et variations", "Exponentielle et logarithme"], exactNotions: "Primitive, exponentielle, variations, racine unique, intégration par parties et volume.", difficulty: "Soutenue", pdfUrl: pdf.y2026j2, correctionHref: "/sujet-bac-maths-2026-corrige#jour-2", methodHref: "/methodes-maths-terminale/integrales" },
] as const;

export const chapterGuides: readonly { name: ChapterName; intro: string; links: readonly { href: string; label: string }[] }[] = [
  { name: "Suites", intro: "Récurrence, monotonie, limites et seuils dans des modèles réellement évalués.", links: [{ href: "/programme-maths-terminale/suites", label: "Programme" }, { href: "/methodes-maths-terminale/etudier-une-suite", label: "Méthode" }, { href: "/exercices-maths-terminale/suites", label: "Exercices" }] },
  { name: "Limites", intro: "Limites de suites et fonctions, asymptotes et interprétations de modèles.", links: [{ href: "/programme-maths-terminale/limites", label: "Programme" }, { href: "/methodes-maths-terminale/calculer-une-limite", label: "Méthode" }, { href: "/exercices-maths-terminale/limites", label: "Exercices" }] },
  { name: "Continuité", intro: "Existence et unicité d’une solution, souvent combinées à la monotonie.", links: [{ href: "/programme-maths-terminale", label: "Programme" }, { href: "/methodes-maths-terminale/tableau-variation", label: "Méthode" }, { href: "/formules-bac-maths-terminale", label: "Formules" }] },
  { name: "Dérivation et variations", intro: "Dériver, dresser un tableau et traduire une variation dans le contexte.", links: [{ href: "/programme-maths-terminale/derivation-convexite", label: "Programme" }, { href: "/methodes-maths-terminale/tableau-variation", label: "Méthode" }, { href: "/exercices-maths-terminale/derivation", label: "Exercices" }] },
  { name: "Convexité", intro: "Signe de la dérivée seconde, point d’inflexion et position par rapport aux tangentes.", links: [{ href: "/programme-maths-terminale/derivation-convexite", label: "Programme" }, { href: "/exercices-maths-terminale/derivation", label: "Exercices" }, { href: "/formules-bac-maths-terminale", label: "Formules" }] },
  { name: "Exponentielle et logarithme", intro: "Études de fonctions, équations, limites et modèles de croissance ou décroissance.", links: [{ href: "/programme-maths-terminale/fonction-logarithme", label: "Programme" }, { href: "/methodes-maths-terminale/logarithme", label: "Méthode" }, { href: "/exercices-maths-terminale/logarithme", label: "Exercices" }] },
  { name: "Primitives et intégrales", intro: "Primitives, intégration par parties, aires et volumes issus de vrais sujets.", links: [{ href: "/programme-maths-terminale/integrales", label: "Programme" }, { href: "/methodes-maths-terminale/integrales", label: "Méthode" }, { href: "/exercices-maths-terminale/integrales", label: "Exercices" }] },
  { name: "Équations différentielles", intro: "Résoudre une EDO, utiliser une condition initiale et interpréter un équilibre.", links: [{ href: "/equations-differentielles-terminale", label: "Cours et méthode" }, { href: "/formules-bac-maths-terminale", label: "Formules" }, { href: "/exercices-type-bac-maths-terminale", label: "Exercices type bac" }] },
  { name: "Probabilités conditionnelles", intro: "Arbres, probabilités totales, Bayes et interprétation des événements.", links: [{ href: "/programme-maths-terminale/probabilites", label: "Programme" }, { href: "/methodes-maths-terminale/probabilites-conditionnelles", label: "Méthode" }, { href: "/exercices-maths-terminale/probabilites", label: "Exercices" }] },
  { name: "Loi binomiale", intro: "Reconnaître les essais de Bernoulli et calculer une probabilité cumulée.", links: [{ href: "/programme-maths-terminale/probabilites", label: "Programme" }, { href: "/exercices-maths-terminale/probabilites", label: "Exercices" }, { href: "/formules-bac-maths-terminale", label: "Formules" }] },
  { name: "Dénombrement", intro: "Combinaisons, arrangements et choix avec ou sans ordre.", links: [{ href: "/denombrement-terminale-specialite-maths", label: "Cours et méthode" }, { href: "/exercices-type-bac-maths-terminale", label: "Exercices type bac" }, { href: "/formules-bac-maths-terminale", label: "Formules" }] },
  { name: "Géométrie dans l’espace", intro: "Plans, droites, orthogonalité, projections, distances, aires et volumes.", links: [{ href: "/programme-maths-terminale/geometrie-espace", label: "Programme" }, { href: "/methodes-maths-terminale/geometrie-espace", label: "Méthode" }, { href: "/exercices-maths-terminale/geometrie-espace", label: "Exercices" }] },
  { name: "Python et algorithmique", intro: "Boucles de seuil et traduction directe d’une relation de récurrence.", links: [{ href: "/python-bac-maths-terminale", label: "Cours et méthode" }, { href: "/exercices-maths-terminale/suites", label: "Exercices de suites" }, { href: "/formules-bac-maths-terminale", label: "Formules" }] },
] as const;
